In [1]:
#imports
import pandas as pd
import numpy as np

#csv -> dataframe
species_df = pd.read_csv('species.csv', dtype = str)
parks_df = pd.read_csv('parks.csv')

species_df.head()
#Note: not sure why there is a 14th data column showing-there are only 13 columns of data-this is confirmed
#in the documentation for the dataset. Will come back and drop that.

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [2]:
#drop that extra column in species_df
species_df = species_df.iloc[: , :-1]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [3]:
#entries where "Record Status" is a Common Name clearly have errors
#entries with "In Review" record status are missing data in some fields,
#may not be as reliable as "Approved" entries
#BUT they make up a substantial portion of the dataset - let's try keeping them in

species_df = species_df[species_df['Record Status'].isin(["Approved", "In Review"])]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [4]:
#what are the possible labels for the "Seasonality" column?
species_df["Seasonality"].value_counts()

Breeder                                 12214
Resident                                 3215
Migratory                                2825
Vagrant                                  1660
Breeder, Winter                            64
Summer                                     26
Migratory, Winter                          24
Winter                                     20
Breeder, Resident                          20
Breeder, Migratory                         13
Resident, Winter                            9
Migratory, Vagrant                          4
Breeder, Resident, Summer                   3
Summer, Vagrant                             3
Migratory, Summer                           3
Breeder, Summer                             2
Resident, Summer                            2
Winter, Vagrant                             1
Breeder, Resident, Migratory, Summer        1
Breeder, Resident, Summer, Winter           1
Name: Seasonality, dtype: int64

In [5]:
#20 labels in "Seasonality"; several have only a few entries - outliers may skew data
#good amount of null values as well
#let's focus on four main "Seasonality" labels

species_df_sea = species_df[species_df['Seasonality'].isin(["Breeder", "Resident", "Vagrant", "Migratory"])]
species_df_sea

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
6,ACAD-1006,Acadia National Park,Mammal,Carnivora,Felidae,Lynx rufus,"Bay Lynx, Bobcat, Red Lynx, Wild Cat",Approved,Not Present (Historical Report),Not Native,NaN,Vagrant,NaN
8,ACAD-1008,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,Common,Breeder,NaN
22,ACAD-1022,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,Occasional,Migratory,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117878,ZION-1426,Zion National Park,Fish,Cypriniformes,Cyprinidae,Rhinichthys osculus,Speckled Dace,Approved,Present,Native,Common,Breeder,NaN
117880,ZION-1428,Zion National Park,Fish,Salmoniformes,Salmonidae,Oncorhynchus clarkii utah,Bonneville Cutthroat Trout,Approved,Present,Not Native,Occasional,Breeder,NaN
117881,ZION-1429,Zion National Park,Fish,Salmoniformes,Salmonidae,Oncorhynchus mykiss,Rainbow Trout,Approved,Present,Not Native,Unknown,Breeder,NaN
117882,ZION-1430,Zion National Park,Fish,Salmoniformes,Salmonidae,Salmo trutta,Brown Trout,Approved,Present,Not Native,Uncommon,Breeder,NaN
117883,ZION-1431,Zion National Park,Fish,Salmoniformes,Salmonidae,Salvelinus fontinalis,Brook Trout,Approved,Present,Not Native,Occasional,Breeder,NaN

In [6]:
#this data is primarily text
#so we will need to do some label encoding before we can create and train data models

#label encode Park Name
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()

def LabelEncode (df):
    for col in df:
        df[col] = class_labels.fit_transform(df[col].values)

In [7]:
#label encode species dataframe
LabelEncode(species_df_sea)
species_df_sea

<ipython-input-6-80ab2d7ab1d4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = class_labels.fit_transform(df[col].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,6,18,156,171,2232,0,4,0,3,2,7
4,1,0,6,32,133,6290,326,0,4,2,1,0,7
6,2,0,6,32,310,3395,270,0,3,1,6,3,7
8,3,0,6,32,497,3370,2547,0,4,0,1,0,7
22,4,0,6,38,817,3098,1232,0,4,0,2,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117878,19909,55,3,53,245,5121,3228,0,4,0,1,0,7
117880,19910,55,3,144,668,4202,515,0,4,1,2,0,7
117881,19911,55,3,144,668,4207,2759,0,4,1,5,0,7
117882,19912,55,3,144,668,5189,590,0,4,1,4,0,7
117883,19913,55,3,144,668,5200,560,0,4,1,2,0,7

In [8]:
#scientific names should be unique - each entry already has unique identifier in "Species ID"
#common names are useful for humans but may just muddy the waters for machine learning/modeling

species_df_filtered = species_df_sea.drop(labels = ["Scientific Name", "Common Names"], axis = 1)

species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,6,18,156,0,4,0,3,2,7
4,1,0,6,32,133,0,4,2,1,0,7
6,2,0,6,32,310,0,3,1,6,3,7
8,3,0,6,32,497,0,4,0,1,0,7
22,4,0,6,38,817,0,4,0,2,1,7

In [9]:
#check data types - see if our label encoding behaved
species_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19914 entries, 0 to 117883
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Species ID           19914 non-null  int64
 1   Park Name            19914 non-null  int64
 2   Category             19914 non-null  int64
 3   Order                19914 non-null  int64
 4   Family               19914 non-null  int64
 5   Record Status        19914 non-null  int64
 6   Occurrence           19914 non-null  int64
 7   Nativeness           19914 non-null  int64
 8   Abundance            19914 non-null  int64
 9   Seasonality          19914 non-null  int64
 10  Conservation Status  19914 non-null  int64
dtypes: int64(11)
memory usage: 1.8 MB

In [10]:
#modeling to predict "Seasonality"
#logistic regression
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_df_filtered.drop('Seasonality', axis=1)
y = species_df_filtered['Seasonality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [11]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [12]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression_sea = LogisticRegression()
regression_sea.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [13]:
#check performance of regression model
regression_sea.fit(X_train, y_train)
y_pred = regression_sea.predict(X_test)
regression_sea.score(X_test, y_test)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.6025608837559628

In [14]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_sea = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_sea)

1.2045399099562368

In [15]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [16]:
X = species_df_filtered.drop('Seasonality', axis=1)
y = species_df_filtered['Seasonality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [17]:
dt_sea = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_sea.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [18]:
y_pred = dt_sea.predict(X_test)

dt_sea_score = accuracy_score(y_test, y_pred)
print(dt_sea_score)

0.7296008034145117

In [19]:
#check rmse
rmse_dt_sea = MSE(y_test, y_pred) ** (1/2)
print(rmse_dt_sea)

0.8749305054717038

In [20]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

#set seed
SEED = 42

X = species_df_filtered.drop('Seasonality', axis=1)
y = species_df_filtered['Seasonality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = SEED)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [21]:
rf_sea = RandomForestRegressor(n_estimators = 400, min_samples_leaf = 0.1, random_state = SEED)
rf_sea.fit(X_train, y_train)

RandomForestRegressor(min_samples_leaf=0.1, n_estimators=400, random_state=42)

In [22]:
y_pred = rf_sea.predict(X_test)

rmse_rf_sea = MSE(y_test, y_pred) ** (1/2)
print(rmse_rf_sea)

0.9374232170683033

In [23]:
#neural network imports
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

X = species_df_filtered.drop('Seasonality', axis=1)
y = species_df_filtered['Seasonality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

number_features = X_train.shape[1]

In [24]:
#defining the model
model_sea = Sequential()
model_sea.add(Dense(100, activation='relu', kernel_initializer='he_normal', input_shape=(number_features,)))
model_sea.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model_sea.add(Dense(5, activation='softmax'))

In [25]:
#compile model
model_sea.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [26]:
#run Abundance neural network model
model_sea.fit(X_train, y_train, epochs=250, batch_size=100, verbose=2)

Epoch 1/250
160/160 - 1s - loss: 1.0318 - accuracy: 0.6069
Epoch 2/250
160/160 - 0s - loss: 0.8000 - accuracy: 0.6791
Epoch 3/250
160/160 - 0s - loss: 0.7597 - accuracy: 0.7020
Epoch 4/250
160/160 - 0s - loss: 0.7295 - accuracy: 0.7192
Epoch 5/250
160/160 - 0s - loss: 0.7086 - accuracy: 0.7232
Epoch 6/250
160/160 - 0s - loss: 0.6909 - accuracy: 0.7318
Epoch 7/250
160/160 - 0s - loss: 0.6777 - accuracy: 0.7351
Epoch 8/250
160/160 - 0s - loss: 0.6691 - accuracy: 0.7340
Epoch 9/250
160/160 - 0s - loss: 0.6618 - accuracy: 0.7372
Epoch 10/250
160/160 - 0s - loss: 0.6509 - accuracy: 0.7431
Epoch 11/250
160/160 - 0s - loss: 0.6453 - accuracy: 0.7433
Epoch 12/250
160/160 - 0s - loss: 0.6410 - accuracy: 0.7443
Epoch 13/250
160/160 - 1s - loss: 0.6374 - accuracy: 0.7480
Epoch 14/250
160/160 - 0s - loss: 0.6327 - accuracy: 0.7477
Epoch 15/250
160/160 - 0s - loss: 0.6275 - accuracy: 0.7475
Epoch 16/250
160/160 - 1s - loss: 0.6285 - accuracy: 0.7464
Epoch 17/250
160/160 - 0s - loss: 0.6207 - accuracy: 0.7500
Epoch 18/250
160/160 - 0s - loss: 0.6170 - accuracy: 0.7511
Epoch 19/250
160/160 - 0s - loss: 0.6179 - accuracy: 0.7512
Epoch 20/250
160/160 - 0s - loss: 0.6131 - accuracy: 0.7540
Epoch 21/250
160/160 - 1s - loss: 0.6116 - accuracy: 0.7531
Epoch 22/250
160/160 - 0s - loss: 0.6084 - accuracy: 0.7554
Epoch 23/250
160/160 - 0s - loss: 0.6088 - accuracy: 0.7544
Epoch 24/250
160/160 - 0s - loss: 0.6058 - accuracy: 0.7543
Epoch 25/250
160/160 - 0s - loss: 0.6034 - accuracy: 0.7590
Epoch 26/250
160/160 - 0s - loss: 0.6021 - accuracy: 0.7593
Epoch 27/250
160/160 - 0s - loss: 0.5964 - accuracy: 0.7610
Epoch 28/250
160/160 - 0s - loss: 0.5974 - accuracy: 0.7584
Epoch 29/250
160/160 - 0s - loss: 0.5939 - accuracy: 0.7608
Epoch 30/250
160/160 - 0s - loss: 0.5950 - accuracy: 0.7597
Epoch 31/250
160/160 - 0s - loss: 0.5932 - accuracy: 0.7612
Epoch 32/250
160/160 - 0s - loss: 0.5898 - accuracy: 0.7621
Epoch 33/250
160/160 - 0s - loss: 0.5895 - accuracy: 0.7635
Epoch 34/250
160/160 - 0s - loss: 0.5858 - accuracy: 0.7625
Epoch 35/250
160/160 - 0s - loss: 0.5845 - accuracy: 0.7626
Epoch 36/250
160/160 - 0s - loss: 0.5833 - accuracy: 0.7642
Epoch 37/250
160/160 - 0s - loss: 0.5844 - accuracy: 0.7659
Epoch 38/250
160/160 - 0s - loss: 0.5826 - accuracy: 0.7635
Epoch 39/250
160/160 - 0s - loss: 0.5802 - accuracy: 0.7657
Epoch 40/250
160/160 - 0s - loss: 0.5779 - accuracy: 0.7662
Epoch 41/250
160/160 - 0s - loss: 0.5784 - accuracy: 0.7679
Epoch 42/250
160/160 - 0s - loss: 0.5756 - accuracy: 0.7659
Epoch 43/250
160/160 - 0s - loss: 0.5754 - accuracy: 0.7662
Epoch 44/250
160/160 - 0s - loss: 0.5739 - accuracy: 0.7685
Epoch 45/250
160/160 - 0s - loss: 0.5727 - accuracy: 0.7688
Epoch 46/250
160/160 - 0s - loss: 0.5738 - accuracy: 0.7668
Epoch 47/250
160/160 - 0s - loss: 0.5702 - accuracy: 0.7689
Epoch 48/250
160/160 - 0s - loss: 0.5720 - accuracy: 0.7675
Epoch 49/250
160/160 - 0s - loss: 0.5710 - accuracy: 0.7661
Epoch 50/250
160/160 - 0s - loss: 0.5688 - accuracy: 0.7674
Epoch 51/250
160/160 - 0s - loss: 0.5644 - accuracy: 0.7697
Epoch 52/250
160/160 - 0s - loss: 0.5709 - accuracy: 0.7683
Epoch 53/250
160/160 - 0s - loss: 0.5653 - accuracy: 0.7714
Epoch 54/250
160/160 - 0s - loss: 0.5671 - accuracy: 0.7675
Epoch 55/250
160/160 - 0s - loss: 0.5616 - accuracy: 0.7731
Epoch 56/250
160/160 - 0s - loss: 0.5611 - accuracy: 0.7713
Epoch 57/250
160/160 - 0s - loss: 0.5603 - accuracy: 0.7738
Epoch 58/250
160/160 - 0s - loss: 0.5601 - accuracy: 0.7741
Epoch 59/250
160/160 - 0s - loss: 0.5622 - accuracy: 0.7702
Epoch 60/250
160/160 - 0s - loss: 0.5562 - accuracy: 0.7742
Epoch 61/250
160/160 - 0s - loss: 0.5574 - accuracy: 0.7718
Epoch 62/250
160/160 - 0s - loss: 0.5565 - accuracy: 0.7739
Epoch 63/250
160/160 - 0s - loss: 0.5539 - accuracy: 0.7721
Epoch 64/250
160/160 - 0s - loss: 0.5537 - accuracy: 0.7760
Epoch 65/250
160/160 - 0s - loss: 0.5570 - accuracy: 0.7747
Epoch 66/250
160/160 - 0s - loss: 0.5506 - accuracy: 0.7760
Epoch 67/250
160/160 - 0s - loss: 0.5531 - accuracy: 0.7730
Epoch 68/250
160/160 - 0s - loss: 0.5513 - accuracy: 0.7752
Epoch 69/250
160/160 - 0s - loss: 0.5495 - accuracy: 0.7759
Epoch 70/250
160/160 - 0s - loss: 0.5482 - accuracy: 0.7766
Epoch 71/250
160/160 - 0s - loss: 0.5482 - accuracy: 0.7787
Epoch 72/250
160/160 - 0s - loss: 0.5451 - accuracy: 0.7797
Epoch 73/250
160/160 - 0s - loss: 0.5458 - accuracy: 0.7782
Epoch 74/250
160/160 - 0s - loss: 0.5465 - accuracy: 0.7784
Epoch 75/250
160/160 - 0s - loss: 0.5431 - accuracy: 0.7786
Epoch 76/250
160/160 - 0s - loss: 0.5451 - accuracy: 0.7787
Epoch 77/250
160/160 - 0s - loss: 0.5447 - accuracy: 0.7775
Epoch 78/250
160/160 - 0s - loss: 0.5434 - accuracy: 0.7784
Epoch 79/250
160/160 - 1s - loss: 0.5433 - accuracy: 0.7808
Epoch 80/250
160/160 - 0s - loss: 0.5449 - accuracy: 0.7780
Epoch 81/250
160/160 - 0s - loss: 0.5477 - accuracy: 0.7776
Epoch 82/250
160/160 - 0s - loss: 0.5394 - accuracy: 0.7800
Epoch 83/250
160/160 - 1s - loss: 0.5423 - accuracy: 0.7768
Epoch 84/250
160/160 - 1s - loss: 0.5385 - accuracy: 0.7810
Epoch 85/250
160/160 - 0s - loss: 0.5398 - accuracy: 0.7787
Epoch 86/250
160/160 - 1s - loss: 0.5394 - accuracy: 0.7800
Epoch 87/250
160/160 - 1s - loss: 0.5382 - accuracy: 0.7808
Epoch 88/250
160/160 - 1s - loss: 0.5397 - accuracy: 0.7758
Epoch 89/250
160/160 - 0s - loss: 0.5361 - accuracy: 0.7797
Epoch 90/250
160/160 - 1s - loss: 0.5345 - accuracy: 0.7819
Epoch 91/250
160/160 - 0s - loss: 0.5353 - accuracy: 0.7830
Epoch 92/250
160/160 - 1s - loss: 0.5351 - accuracy: 0.7798
Epoch 93/250
160/160 - 0s - loss: 0.5330 - accuracy: 0.7841
Epoch 94/250
160/160 - 0s - loss: 0.5323 - accuracy: 0.7814
Epoch 95/250
160/160 - 0s - loss: 0.5347 - accuracy: 0.7810
Epoch 96/250
160/160 - 0s - loss: 0.5307 - accuracy: 0.7822
Epoch 97/250
160/160 - 0s - loss: 0.5314 - accuracy: 0.7816
Epoch 98/250
160/160 - 0s - loss: 0.5316 - accuracy: 0.7832
Epoch 99/250
160/160 - 0s - loss: 0.5323 - accuracy: 0.7839
Epoch 100/250
160/160 - 0s - loss: 0.5289 - accuracy: 0.7838
Epoch 101/250
160/160 - 0s - loss: 0.5307 - accuracy: 0.7827
Epoch 102/250
160/160 - 0s - loss: 0.5283 - accuracy: 0.7823
Epoch 103/250
160/160 - 0s - loss: 0.5270 - accuracy: 0.7856
Epoch 104/250
160/160 - 0s - loss: 0.5274 - accuracy: 0.7841
Epoch 105/250
160/160 - 0s - loss: 0.5265 - accuracy: 0.7828
Epoch 106/250
160/160 - 0s - loss: 0.5259 - accuracy: 0.7847
Epoch 107/250
160/160 - 0s - loss: 0.5274 - accuracy: 0.7816
Epoch 108/250
160/160 - 0s - loss: 0.5255 - accuracy: 0.7861
Epoch 109/250
160/160 - 0s - loss: 0.5246 - accuracy: 0.7868
Epoch 110/250
160/160 - 0s - loss: 0.5281 - accuracy: 0.7849
Epoch 111/250
160/160 - 0s - loss: 0.5266 - accuracy: 0.7847
Epoch 112/250
160/160 - 0s - loss: 0.5233 - accuracy: 0.7875
Epoch 113/250
160/160 - 0s - loss: 0.5263 - accuracy: 0.7840
Epoch 114/250
160/160 - 0s - loss: 0.5217 - accuracy: 0.7853
Epoch 115/250
160/160 - 0s - loss: 0.5209 - accuracy: 0.7868
Epoch 116/250
160/160 - 0s - loss: 0.5226 - accuracy: 0.7858
Epoch 117/250
160/160 - 0s - loss: 0.5218 - accuracy: 0.7863
Epoch 118/250
160/160 - 0s - loss: 0.5218 - accuracy: 0.7862
Epoch 119/250
160/160 - 0s - loss: 0.5231 - accuracy: 0.7854
Epoch 120/250
160/160 - 0s - loss: 0.5195 - accuracy: 0.7873
Epoch 121/250
160/160 - 0s - loss: 0.5208 - accuracy: 0.7876
Epoch 122/250
160/160 - 0s - loss: 0.5175 - accuracy: 0.7851
Epoch 123/250
160/160 - 0s - loss: 0.5168 - accuracy: 0.7890
Epoch 124/250
160/160 - 0s - loss: 0.5190 - accuracy: 0.7876
Epoch 125/250
160/160 - 0s - loss: 0.5160 - accuracy: 0.7881
Epoch 126/250
160/160 - 0s - loss: 0.5201 - accuracy: 0.7871
Epoch 127/250
160/160 - 0s - loss: 0.5194 - accuracy: 0.7883
Epoch 128/250
160/160 - 0s - loss: 0.5176 - accuracy: 0.7860
Epoch 129/250
160/160 - 0s - loss: 0.5175 - accuracy: 0.7875
Epoch 130/250
160/160 - 0s - loss: 0.5134 - accuracy: 0.7887
Epoch 131/250
160/160 - 0s - loss: 0.5126 - accuracy: 0.7907
Epoch 132/250
160/160 - 0s - loss: 0.5136 - accuracy: 0.7897
Epoch 133/250
160/160 - 0s - loss: 0.5146 - accuracy: 0.7877
Epoch 134/250
160/160 - 0s - loss: 0.5117 - accuracy: 0.7908
Epoch 135/250
160/160 - 0s - loss: 0.5133 - accuracy: 0.7892
Epoch 136/250
160/160 - 0s - loss: 0.5116 - accuracy: 0.7888
Epoch 137/250

160/160 - 0s - loss: 0.5110 - accuracy: 0.7875
Epoch 138/250
160/160 - 0s - loss: 0.5108 - accuracy: 0.7880
Epoch 139/250
160/160 - 0s - loss: 0.5100 - accuracy: 0.7907
Epoch 140/250
160/160 - 0s - loss: 0.5113 - accuracy: 0.7890
Epoch 141/250
160/160 - 0s - loss: 0.5083 - accuracy: 0.7899
Epoch 142/250
160/160 - 0s - loss: 0.5107 - accuracy: 0.7877
Epoch 143/250
160/160 - 0s - loss: 0.5089 - accuracy: 0.7922
Epoch 144/250
160/160 - 0s - loss: 0.5099 - accuracy: 0.7887
Epoch 145/250
160/160 - 0s - loss: 0.5108 - accuracy: 0.7906
Epoch 146/250
160/160 - 0s - loss: 0.5094 - accuracy: 0.7896
Epoch 147/250
160/160 - 0s - loss: 0.5099 - accuracy: 0.7878
Epoch 148/250
160/160 - 0s - loss: 0.5116 - accuracy: 0.7880
Epoch 149/250
160/160 - 0s - loss: 0.5073 - accuracy: 0.7930
Epoch 150/250
160/160 - 0s - loss: 0.5068 - accuracy: 0.7922
Epoch 151/250
160/160 - 0s - loss: 0.5090 - accuracy: 0.7919
Epoch 152/250
160/160 - 0s - loss: 0.5091 - accuracy: 0.7887
Epoch 153/250
160/160 - 0s - loss: 0.5044 - accuracy: 0.7924
Epoch 154/250
160/160 - 0s - loss: 0.5075 - accuracy: 0.7896
Epoch 155/250
160/160 - 0s - loss: 0.5064 - accuracy: 0.7913
Epoch 156/250
160/160 - 0s - loss: 0.5069 - accuracy: 0.7890
Epoch 157/250
160/160 - 0s - loss: 0.5051 - accuracy: 0.7903
Epoch 158/250
160/160 - 0s - loss: 0.5052 - accuracy: 0.7937
Epoch 159/250
160/160 - 0s - loss: 0.5035 - accuracy: 0.7919
Epoch 160/250
160/160 - 0s - loss: 0.5044 - accuracy: 0.7897
Epoch 161/250
160/160 - 0s - loss: 0.5008 - accuracy: 0.7935
Epoch 162/250
160/160 - 0s - loss: 0.5012 - accuracy: 0.7953
Epoch 163/250
160/160 - 0s - loss: 0.5023 - accuracy: 0.7921
Epoch 164/250
160/160 - 0s - loss: 0.4994 - accuracy: 0.7966
Epoch 165/250
160/160 - 0s - loss: 0.4998 - accuracy: 0.7939
Epoch 166/250
160/160 - 0s - loss: 0.4980 - accuracy: 0.7954
Epoch 167/250
160/160 - 0s - loss: 0.4988 - accuracy: 0.7946
Epoch 168/250
160/160 - 0s - loss: 0.4999 - accuracy: 0.7944
Epoch 169/250
160/160 - 0s - loss: 0.5003 - accuracy: 0.7942
Epoch 170/250
160/160 - 0s - loss: 0.4982 - accuracy: 0.7939
Epoch 171/250
160/160 - 0s - loss: 0.5007 - accuracy: 0.7948
Epoch 172/250
160/160 - 0s - loss: 0.4998 - accuracy: 0.7952
Epoch 173/250
160/160 - 0s - loss: 0.4985 - accuracy: 0.7934
Epoch 174/250
160/160 - 0s - loss: 0.4994 - accuracy: 0.7943
Epoch 175/250
160/160 - 0s - loss: 0.5005 - accuracy: 0.7927
Epoch 176/250
160/160 - 0s - loss: 0.4994 - accuracy: 0.7937
Epoch 177/250
160/160 - 0s - loss: 0.4974 - accuracy: 0.7965
Epoch 178/250
160/160 - 0s - loss: 0.4937 - accuracy: 0.7973
Epoch 179/250
160/160 - 0s - loss: 0.4951 - accuracy: 0.7953
Epoch 180/250
160/160 - 0s - loss: 0.4967 - accuracy: 0.7927
Epoch 181/250
160/160 - 0s - loss: 0.4934 - accuracy: 0.7991
Epoch 182/250
160/160 - 0s - loss: 0.4958 - accuracy: 0.7961
Epoch 183/250
160/160 - 0s - loss: 0.4973 - accuracy: 0.7961
Epoch 184/250
160/160 - 0s - loss: 0.4927 - accuracy: 0.7966
Epoch 185/250
160/160 - 0s - loss: 0.4948 - accuracy: 0.7962
Epoch 186/250
160/160 - 0s - loss: 0.4987 - accuracy: 0.7951
Epoch 187/250
160/160 - 0s - loss: 0.4952 - accuracy: 0.7989
Epoch 188/250
160/160 - 0s - loss: 0.4930 - accuracy: 0.7954
Epoch 189/250
160/160 - 0s - loss: 0.4947 - accuracy: 0.7962
Epoch 190/250
160/160 - 0s - loss: 0.4936 - accuracy: 0.7959
Epoch 191/250
160/160 - 0s - loss: 0.4942 - accuracy: 0.7976
Epoch 192/250
160/160 - 0s - loss: 0.4925 - accuracy: 0.7942
Epoch 193/250
160/160 - 0s - loss: 0.4907 - accuracy: 0.7974
Epoch 194/250
160/160 - 0s - loss: 0.4912 - accuracy: 0.7978
Epoch 195/250
160/160 - 0s - loss: 0.4903 - accuracy: 0.7977
Epoch 196/250
160/160 - 0s - loss: 0.4969 - accuracy: 0.7940
Epoch 197/250
160/160 - 0s - loss: 0.4899 - accuracy: 0.7978
Epoch 198/250
160/160 - 0s - loss: 0.4916 - accuracy: 0.7969
Epoch 199/250
160/160 - 0s - loss: 0.4909 - accuracy: 0.7978
Epoch 200/250
160/160 - 0s - loss: 0.4906 - accuracy: 0.7939
Epoch 201/250
160/160 - 0s - loss: 0.4902 - accuracy: 0.7944
Epoch 202/250
160/160 - 0s - loss: 0.4920 - accuracy: 0.7978
Epoch 203/250
160/160 - 0s - loss: 0.4906 - accuracy: 0.7989
Epoch 204/250
160/160 - 0s - loss: 0.4898 - accuracy: 0.7966
Epoch 205/250
160/160 - 0s - loss: 0.4894 - accuracy: 0.7966
Epoch 206/250
160/160 - 0s - loss: 0.4861 - accuracy: 0.7994
Epoch 207/250
160/160 - 0s - loss: 0.4890 - accuracy: 0.8000
Epoch 208/250
160/160 - 0s - loss: 0.4894 - accuracy: 0.7954
Epoch 209/250
160/160 - 0s - loss: 0.4913 - accuracy: 0.7940
Epoch 210/250
160/160 - 0s - loss: 0.4875 - accuracy: 0.7971
Epoch 211/250
160/160 - 0s - loss: 0.4868 - accuracy: 0.8001
Epoch 212/250
160/160 - 0s - loss: 0.4888 - accuracy: 0.7962
Epoch 213/250
160/160 - 0s - loss: 0.4857 - accuracy: 0.7995
Epoch 214/250
160/160 - 0s - loss: 0.4879 - accuracy: 0.7983
Epoch 215/250
160/160 - 0s - loss: 0.4891 - accuracy: 0.7984
Epoch 216/250
160/160 - 0s - loss: 0.4861 - accuracy: 0.7989
Epoch 217/250
160/160 - 0s - loss: 0.4837 - accuracy: 0.8007
Epoch 218/250
160/160 - 0s - loss: 0.4836 - accuracy: 0.8018
Epoch 219/250
160/160 - 0s - loss: 0.4863 - accuracy: 0.7959
Epoch 220/250
160/160 - 0s - loss: 0.4840 - accuracy: 0.8005
Epoch 221/250
160/160 - 0s - loss: 0.4869 - accuracy: 0.7984
Epoch 222/250
160/160 - 0s - loss: 0.4854 - accuracy: 0.7988
Epoch 223/250
160/160 - 0s - loss: 0.4848 - accuracy: 0.7972
Epoch 224/250
160/160 - 0s - loss: 0.4840 - accuracy: 0.8010
Epoch 225/250
160/160 - 0s - loss: 0.4834 - accuracy: 0.7985
Epoch 226/250
160/160 - 0s - loss: 0.4836 - accuracy: 0.7989
Epoch 227/250
160/160 - 0s - loss: 0.4836 - accuracy: 0.7999
Epoch 228/250
160/160 - 0s - loss: 0.4831 - accuracy: 0.8020
Epoch 229/250
160/160 - 0s - loss: 0.4826 - accuracy: 0.8010
Epoch 230/250
160/160 - 0s - loss: 0.4814 - accuracy: 0.7998
Epoch 231/250
160/160 - 0s - loss: 0.4833 - accuracy: 0.7998
Epoch 232/250
160/160 - 0s - loss: 0.4796 - accuracy: 0.8027
Epoch 233/250
160/160 - 0s - loss: 0.4798 - accuracy: 0.8011
Epoch 234/250
160/160 - 0s - loss: 0.4811 - accuracy: 0.8020
Epoch 235/250
160/160 - 0s - loss: 0.4780 - accuracy: 0.8015
Epoch 236/250
160/160 - 0s - loss: 0.4787 - accuracy: 0.8037
Epoch 237/250
160/160 - 0s - loss: 0.4804 - accuracy: 0.8006
Epoch 238/250
160/160 - 0s - loss: 0.4836 - accuracy: 0.7975
Epoch 239/250
160/160 - 0s - loss: 0.4792 - accuracy: 0.8027
Epoch 240/250
160/160 - 0s - loss: 0.4795 - accuracy: 0.7997
Epoch 241/250
160/160 - 0s - loss: 0.4796 - accuracy: 0.8010
Epoch 242/250
160/160 - 0s - loss: 0.4794 - accuracy: 0.8010
Epoch 243/250
160/160 - 0s - loss: 0.4787 - accuracy: 0.8033
Epoch 244/250
160/160 - 0s - loss: 0.4820 - accuracy: 0.7983
Epoch 245/250
160/160 - 0s - loss: 0.4773 - accuracy: 0.8033
Epoch 246/250
160/160 - 0s - loss: 0.4807 - accuracy: 0.8028
Epoch 247/250
160/160 - 0s - loss: 0.4758 - accuracy: 0.8031
Epoch 248/250
160/160 - 0s - loss: 0.4780 - accuracy: 0.8029
Epoch 249/250
160/160 - 0s - loss: 0.4760 - accuracy: 0.8013
Epoch 250/250
160/160 - 0s - loss: 0.4747 - accuracy: 0.8050

Of the models, the neural network performed best with about 80% accuracy.  All Seasonality models performed better than the Abundance models, but not nearly as well as the Nativeness models.