In [1]:
#imports
import pandas as pd
import numpy as np

#csv -> dataframe
species_df = pd.read_csv('species.csv', dtype = str)
parks_df = pd.read_csv('parks.csv')

species_df.head()
#Note: not sure why there is a 14th data column showing-there are only 13 columns of data-this is confirmed
#in the documentation for the dataset. Will come back and drop that.

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [2]:
#drop that extra column in species_df
species_df = species_df.iloc[: , :-1]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [3]:
#entries where "Record Status" is a Common Name clearly have errors
#entries with "In Review" record status are missing data in some fields,
#may not be as reliable as "Approved" entries
#BUT they make up a substantial portion of the dataset - let's try keeping them in

species_df = species_df[species_df['Record Status'].isin(["Approved", "In Review"])]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [4]:
#what are the possible labels for the "Abundance" column?
species_df["Abundance"].value_counts()

Unknown       28118
Uncommon      18779
Common        12913
Rare          10768
Occasional     3312
Abundant       2365
Name: Abundance, dtype: int64

In [5]:
#this data is primarily text
#so we will need to do some label encoding before we can create and train data models

#label encode Park Name
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()

def LabelEncode (df):
    for col in df:
        df[col] = class_labels.fit_transform(df[col].values)

In [6]:
#label encode species dataframe
LabelEncode(species_df)
species_df

<ipython-input-5-80ab2d7ab1d4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = class_labels.fit_transform(df[col].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,1130,20527,0,4,0,3,12,8
1,1,0,8,41,417,29730,22166,0,4,0,0,20,8
2,2,0,8,87,352,7202,8773,0,4,1,1,20,5
3,3,0,8,87,352,7204,11183,0,0,0,6,20,0
4,4,0,8,87,352,45436,3332,0,4,2,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,119186,55,13,474,2012,40595,9304,0,4,0,4,20,8
119244,119187,55,13,546,2301,45396,6190,0,4,0,4,20,8
119245,119188,55,13,546,2301,45411,34671,0,4,1,4,20,8
119246,119189,55,13,553,2331,23324,8952,0,4,0,3,20,8
119247,119190,55,13,553,2331,43839,24780,0,4,1,4,20,8

In [7]:
#scientific names should be unique - each entry already has unique identifier in "Species ID"
#common names are useful for humans but may just muddy the waters for machine learning/modeling

species_df_filtered = species_df.drop(labels = ["Scientific Name", "Common Names"], axis = 1)

species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,0,4,0,3,12,8
1,1,0,8,41,417,0,4,0,0,20,8
2,2,0,8,87,352,0,4,1,1,20,5
3,3,0,8,87,352,0,0,0,6,20,0
4,4,0,8,87,352,0,4,2,1,0,8

In [8]:
#check data types - see if our label encoding behaved
species_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119191 entries, 0 to 119247
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Species ID           119191 non-null  int64
 1   Park Name            119191 non-null  int64
 2   Category             119191 non-null  int64
 3   Order                119191 non-null  int64
 4   Family               119191 non-null  int64
 5   Record Status        119191 non-null  int64
 6   Occurrence           119191 non-null  int64
 7   Nativeness           119191 non-null  int64
 8   Abundance            119191 non-null  int64
 9   Seasonality          119191 non-null  int64
 10  Conservation Status  119191 non-null  int64
dtypes: int64(11)
memory usage: 10.9 MB

In [9]:
#modeling to predict "Abundance"
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_df_filtered.drop('Abundance', axis=1)
y = species_df_filtered['Abundance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [10]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [11]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression_ab = LogisticRegression()
regression_ab.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [12]:
#check performance of regression model
regression_ab.fit(X_train, y_train)
y_pred = regression_ab.predict(X_test)
regression_ab.score(X_test, y_test)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5424724191450984

In [13]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_ab = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_ab)

1.6909483075926537

In [14]:
#not so hot scores
#maybe dropping zero values in "Abundance" column will help

species_df_filtab = species_df_filtered[species_df_filtered['Abundance'] > 0]

species_df_filtab

,Species ID,Park Name,Category,Order,Family,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,0,4,0,3,12,8
2,2,0,8,87,352,0,4,1,1,20,5
3,3,0,8,87,352,0,0,0,6,20,0
4,4,0,8,87,352,0,4,2,1,0,8
5,5,0,8,87,863,0,0,0,6,20,8
...,...,...,...,...,...,...,...,...,...,...,...
119243,119186,55,13,474,2012,0,4,0,4,20,8
119244,119187,55,13,546,2301,0,4,0,4,20,8
119245,119188,55,13,546,2301,0,4,1,4,20,8
119246,119189,55,13,553,2331,0,4,0,3,20,8
119247,119190,55,13,553,2331,0,4,1,4,20,8

In [15]:
#modeling to predict "Abundance"
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_df_filtab.drop('Abundance', axis=1)
y = species_df_filtab['Abundance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [16]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [17]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression_ab = LogisticRegression()
regression_ab.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [18]:
#check performance of regression model
regression_ab.fit(X_train, y_train)
y_pred = regression_ab.predict(X_test)
regression_ab.score(X_test, y_test)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5612000342377814

In [19]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_ab = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_ab)

1.5810711602791006

In [20]:
#slightly better scores; let's try other modeling methods

#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [21]:
X = species_df_filtab.drop('Abundance', axis=1)
y = species_df_filtab['Abundance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [22]:
dt_ab = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_ab.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [23]:
y_pred = dt_ab.predict(X_test)

dt_ab_score = accuracy_score(y_test, y_pred)
print(dt_ab_score)

0.607164255756227

In [24]:
#check rmse
rmse_dt_ab = MSE(y_test, y_pred) ** (1/2)
print(rmse_dt_ab)

1.5156181405707203

In [33]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

#set seed
SEED = 42

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = SEED)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [26]:
rf_ab = RandomForestRegressor(n_estimators = 400, min_samples_leaf = 0.1, random_state = SEED)
rf_ab.fit(X_train, y_train)

RandomForestRegressor(min_samples_leaf=0.1, n_estimators=400, random_state=42)

In [27]:
y_pred = rf_ab.predict(X_test)

rmse_rf_ab = MSE(y_test, y_pred) ** (1/2)
print(rmse_rf_ab)

1.3738678074942903

In [34]:
#neural network imports
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

number_features = X_train.shape[1]

In [35]:
#defining the model
model = Sequential()
model.add(Dense(100, activation='relu', kernel_initializer='he_normal', input_shape=(number_features,)))
model.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(7, activation='softmax'))

In [36]:
#compile model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [37]:
#run Abundance neural network model
model.fit(X_train, y_train, epochs=250, batch_size=100, verbose=2)

Epoch 1/250
935/935 - 1s - loss: 0.9133 - accuracy: 0.6206
Epoch 2/250
935/935 - 1s - loss: 0.8259 - accuracy: 0.6586
Epoch 3/250
935/935 - 1s - loss: 0.7991 - accuracy: 0.6726
Epoch 4/250
935/935 - 1s - loss: 0.7819 - accuracy: 0.6807
Epoch 5/250
935/935 - 1s - loss: 0.7682 - accuracy: 0.6851
Epoch 6/250
935/935 - 1s - loss: 0.7554 - accuracy: 0.6905
Epoch 7/250
935/935 - 3s - loss: 0.7455 - accuracy: 0.6957
Epoch 8/250
935/935 - 2s - loss: 0.7374 - accuracy: 0.6982
Epoch 9/250
935/935 - 4s - loss: 0.7312 - accuracy: 0.7023
Epoch 10/250
935/935 - 1s - loss: 0.7255 - accuracy: 0.7033
Epoch 11/250
935/935 - 2s - loss: 0.7214 - accuracy: 0.7047
Epoch 12/250
935/935 - 1s - loss: 0.7179 - accuracy: 0.7060
Epoch 13/250
935/935 - 1s - loss: 0.7138 - accuracy: 0.7075
Epoch 14/250
935/935 - 2s - loss: 0.7106 - accuracy: 0.7071
Epoch 15/250
935/935 - 2s - loss: 0.7086 - accuracy: 0.7083
Epoch 16/250
935/935 - 2s - loss: 0.7053 - accuracy: 0.7077
Epoch 17/250
935/935 - 1s - loss: 0.7028 - accuracy: 0.7086
Epoch 18/250
935/935 - 1s - loss: 0.6989 - accuracy: 0.7104
Epoch 19/250
935/935 - 2s - loss: 0.6969 - accuracy: 0.7117
Epoch 20/250
935/935 - 2s - loss: 0.6944 - accuracy: 0.7103
Epoch 21/250
935/935 - 2s - loss: 0.6915 - accuracy: 0.7124
Epoch 22/250
935/935 - 1s - loss: 0.6882 - accuracy: 0.7123
Epoch 23/250
935/935 - 2s - loss: 0.6863 - accuracy: 0.7149
Epoch 24/250
935/935 - 2s - loss: 0.6835 - accuracy: 0.7151
Epoch 25/250
935/935 - 3s - loss: 0.6810 - accuracy: 0.7154
Epoch 26/250
935/935 - 3s - loss: 0.6785 - accuracy: 0.7174
Epoch 27/250
935/935 - 3s - loss: 0.6760 - accuracy: 0.7193
Epoch 28/250
935/935 - 3s - loss: 0.6733 - accuracy: 0.7210
Epoch 29/250
935/935 - 2s - loss: 0.6700 - accuracy: 0.7215
Epoch 30/250
935/935 - 3s - loss: 0.6685 - accuracy: 0.7216
Epoch 31/250
935/935 - 2s - loss: 0.6660 - accuracy: 0.7229
Epoch 32/250
935/935 - 2s - loss: 0.6637 - accuracy: 0.7238
Epoch 33/250
935/935 - 3s - loss: 0.6611 - accuracy: 0.7249
Epoch 34/250
935/935 - 2s - loss: 0.6590 - accuracy: 0.7266
Epoch 35/250
935/935 - 3s - loss: 0.6569 - accuracy: 0.7273
Epoch 36/250
935/935 - 2s - loss: 0.6538 - accuracy: 0.7277
Epoch 37/250
935/935 - 1s - loss: 0.6516 - accuracy: 0.7301
Epoch 38/250
935/935 - 2s - loss: 0.6496 - accuracy: 0.7316
Epoch 39/250
935/935 - 2s - loss: 0.6476 - accuracy: 0.7307
Epoch 40/250
935/935 - 1s - loss: 0.6464 - accuracy: 0.7313
Epoch 41/250
935/935 - 1s - loss: 0.6438 - accuracy: 0.7323
Epoch 42/250
935/935 - 2s - loss: 0.6411 - accuracy: 0.7337
Epoch 43/250
935/935 - 2s - loss: 0.6390 - accuracy: 0.7348
Epoch 44/250
935/935 - 1s - loss: 0.6373 - accuracy: 0.7359
Epoch 45/250
935/935 - 1s - loss: 0.6360 - accuracy: 0.7362
Epoch 46/250
935/935 - 1s - loss: 0.6337 - accuracy: 0.7375
Epoch 47/250
935/935 - 1s - loss: 0.6318 - accuracy: 0.7394
Epoch 48/250
935/935 - 1s - loss: 0.6295 - accuracy: 0.7402
Epoch 49/250
935/935 - 1s - loss: 0.6284 - accuracy: 0.7413
Epoch 50/250
935/935 - 1s - loss: 0.6266 - accuracy: 0.7401
Epoch 51/250
935/935 - 1s - loss: 0.6250 - accuracy: 0.7424
Epoch 52/250
935/935 - 1s - loss: 0.6227 - accuracy: 0.7427
Epoch 53/250
935/935 - 1s - loss: 0.6203 - accuracy: 0.7443
Epoch 54/250
935/935 - 1s - loss: 0.6195 - accuracy: 0.7449
Epoch 55/250
935/935 - 1s - loss: 0.6163 - accuracy: 0.7466
Epoch 56/250
935/935 - 1s - loss: 0.6147 - accuracy: 0.7477
Epoch 57/250
935/935 - 1s - loss: 0.6142 - accuracy: 0.7476
Epoch 58/250
935/935 - 1s - loss: 0.6115 - accuracy: 0.7484
Epoch 59/250
935/935 - 1s - loss: 0.6111 - accuracy: 0.7486
Epoch 60/250
935/935 - 1s - loss: 0.6097 - accuracy: 0.7495
Epoch 61/250
935/935 - 1s - loss: 0.6078 - accuracy: 0.7484
Epoch 62/250
935/935 - 1s - loss: 0.6065 - accuracy: 0.7501
Epoch 63/250
935/935 - 1s - loss: 0.6044 - accuracy: 0.7503
Epoch 64/250
935/935 - 1s - loss: 0.6035 - accuracy: 0.7510
Epoch 65/250
935/935 - 1s - loss: 0.6018 - accuracy: 0.7512
Epoch 66/250
935/935 - 1s - loss: 0.5998 - accuracy: 0.7524
Epoch 67/250
935/935 - 1s - loss: 0.5994 - accuracy: 0.7529
Epoch 68/250
935/935 - 1s - loss: 0.5984 - accuracy: 0.7527
Epoch 69/250
935/935 - 1s - loss: 0.5958 - accuracy: 0.7542
Epoch 70/250
935/935 - 1s - loss: 0.5962 - accuracy: 0.7537
Epoch 71/250
935/935 - 1s - loss: 0.5956 - accuracy: 0.7550
Epoch 72/250
935/935 - 1s - loss: 0.5932 - accuracy: 0.7549
Epoch 73/250
935/935 - 1s - loss: 0.5925 - accuracy: 0.7548
Epoch 74/250
935/935 - 1s - loss: 0.5907 - accuracy: 0.7560
Epoch 75/250
935/935 - 1s - loss: 0.5899 - accuracy: 0.7556
Epoch 76/250
935/935 - 1s - loss: 0.5903 - accuracy: 0.7558
Epoch 77/250
935/935 - 1s - loss: 0.5880 - accuracy: 0.7560
Epoch 78/250
935/935 - 1s - loss: 0.5879 - accuracy: 0.7560
Epoch 79/250
935/935 - 1s - loss: 0.5864 - accuracy: 0.7563
Epoch 80/250
935/935 - 1s - loss: 0.5862 - accuracy: 0.7571
Epoch 81/250
935/935 - 1s - loss: 0.5852 - accuracy: 0.7572
Epoch 82/250
935/935 - 1s - loss: 0.5844 - accuracy: 0.7575
Epoch 83/250
935/935 - 1s - loss: 0.5838 - accuracy: 0.7580
Epoch 84/250
935/935 - 1s - loss: 0.5825 - accuracy: 0.7578
Epoch 85/250
935/935 - 3s - loss: 0.5822 - accuracy: 0.7581
Epoch 86/250
935/935 - 4s - loss: 0.5820 - accuracy: 0.7577
Epoch 87/250
935/935 - 4s - loss: 0.5805 - accuracy: 0.7593
Epoch 88/250
935/935 - 2s - loss: 0.5802 - accuracy: 0.7594
Epoch 89/250
935/935 - 2s - loss: 0.5808 - accuracy: 0.7583
Epoch 90/250
935/935 - 1s - loss: 0.5784 - accuracy: 0.7592
Epoch 91/250
935/935 - 2s - loss: 0.5781 - accuracy: 0.7594
Epoch 92/250
935/935 - 2s - loss: 0.5781 - accuracy: 0.7603
Epoch 93/250
935/935 - 2s - loss: 0.5776 - accuracy: 0.7609
Epoch 94/250
935/935 - 3s - loss: 0.5762 - accuracy: 0.7607
Epoch 95/250
935/935 - 2s - loss: 0.5773 - accuracy: 0.7603
Epoch 96/250
935/935 - 2s - loss: 0.5757 - accuracy: 0.7597
Epoch 97/250
935/935 - 2s - loss: 0.5751 - accuracy: 0.7608
Epoch 98/250
935/935 - 1s - loss: 0.5748 - accuracy: 0.7608
Epoch 99/250
935/935 - 2s - loss: 0.5747 - accuracy: 0.7605
Epoch 100/250
935/935 - 1s - loss: 0.5739 - accuracy: 0.7610
Epoch 101/250
935/935 - 1s - loss: 0.5726 - accuracy: 0.7616
Epoch 102/250
935/935 - 1s - loss: 0.5726 - accuracy: 0.7607
Epoch 103/250
935/935 - 1s - loss: 0.5720 - accuracy: 0.7622
Epoch 104/250
935/935 - 2s - loss: 0.5711 - accuracy: 0.7621
Epoch 105/250
935/935 - 2s - loss: 0.5716 - accuracy: 0.7614
Epoch 106/250
935/935 - 2s - loss: 0.5709 - accuracy: 0.7622
Epoch 107/250
935/935 - 3s - loss: 0.5697 - accuracy: 0.7625
Epoch 108/250
935/935 - 2s - loss: 0.5694 - accuracy: 0.7623
Epoch 109/250
935/935 - 3s - loss: 0.5697 - accuracy: 0.7624
Epoch 110/250
935/935 - 2s - loss: 0.5689 - accuracy: 0.7629
Epoch 111/250
935/935 - 2s - loss: 0.5690 - accuracy: 0.7624
Epoch 112/250
935/935 - 2s - loss: 0.5686 - accuracy: 0.7628
Epoch 113/250
935/935 - 2s - loss: 0.5680 - accuracy: 0.7639
Epoch 114/250
935/935 - 1s - loss: 0.5685 - accuracy: 0.7635
Epoch 115/250
935/935 - 1s - loss: 0.5658 - accuracy: 0.7638
Epoch 116/250
935/935 - 1s - loss: 0.5663 - accuracy: 0.7646
Epoch 117/250
935/935 - 1s - loss: 0.5659 - accuracy: 0.7634
Epoch 118/250
935/935 - 2s - loss: 0.5667 - accuracy: 0.7637
Epoch 119/250
935/935 - 2s - loss: 0.5645 - accuracy: 0.7640
Epoch 120/250
935/935 - 2s - loss: 0.5644 - accuracy: 0.7648
Epoch 121/250
935/935 - 3s - loss: 0.5650 - accuracy: 0.7638
Epoch 122/250
935/935 - 3s - loss: 0.5646 - accuracy: 0.7634
Epoch 123/250
935/935 - 2s - loss: 0.5641 - accuracy: 0.7639
Epoch 124/250
935/935 - 2s - loss: 0.5639 - accuracy: 0.7649
Epoch 125/250
935/935 - 2s - loss: 0.5627 - accuracy: 0.7643
Epoch 126/250
935/935 - 2s - loss: 0.5627 - accuracy: 0.7661
Epoch 127/250
935/935 - 3s - loss: 0.5626 - accuracy: 0.7646
Epoch 128/250
935/935 - 2s - loss: 0.5619 - accuracy: 0.7666
Epoch 129/250
935/935 - 2s - loss: 0.5625 - accuracy: 0.7658
Epoch 130/250
935/935 - 1s - loss: 0.5600 - accuracy: 0.7660
Epoch 131/250
935/935 - 1s - loss: 0.5620 - accuracy: 0.7652
Epoch 132/250
935/935 - 2s - loss: 0.5597 - accuracy: 0.7670
Epoch 133/250
935/935 - 1s - loss: 0.5601 - accuracy: 0.7658
Epoch 134/250
935/935 - 2s - loss: 0.5598 - accuracy: 0.7659
Epoch 135/250
935/935 - 3s - loss: 0.5596 - accuracy: 0.7662
Epoch 136/250
935/935 - 2s - loss: 0.5594 - accuracy: 0.7671
Epoch 137/250

935/935 - 2s - loss: 0.5576 - accuracy: 0.7676
Epoch 138/250
935/935 - 2s - loss: 0.5575 - accuracy: 0.7662
Epoch 139/250
935/935 - 2s - loss: 0.5585 - accuracy: 0.7659
Epoch 140/250
935/935 - 1s - loss: 0.5577 - accuracy: 0.7682
Epoch 141/250
935/935 - 2s - loss: 0.5573 - accuracy: 0.7676
Epoch 142/250
935/935 - 2s - loss: 0.5560 - accuracy: 0.7670
Epoch 143/250
935/935 - 2s - loss: 0.5572 - accuracy: 0.7668
Epoch 144/250
935/935 - 3s - loss: 0.5570 - accuracy: 0.7671
Epoch 145/250
935/935 - 2s - loss: 0.5564 - accuracy: 0.7676
Epoch 146/250
935/935 - 4s - loss: 0.5557 - accuracy: 0.7684
Epoch 147/250
935/935 - 2s - loss: 0.5550 - accuracy: 0.7681
Epoch 148/250
935/935 - 3s - loss: 0.5549 - accuracy: 0.7680
Epoch 149/250
935/935 - 2s - loss: 0.5535 - accuracy: 0.7675
Epoch 150/250
935/935 - 1s - loss: 0.5539 - accuracy: 0.7691
Epoch 151/250
935/935 - 1s - loss: 0.5534 - accuracy: 0.7688
Epoch 152/250
935/935 - 2s - loss: 0.5533 - accuracy: 0.7686
Epoch 153/250
935/935 - 2s - loss: 0.5535 - accuracy: 0.7683
Epoch 154/250
935/935 - 2s - loss: 0.5529 - accuracy: 0.7693
Epoch 155/250
935/935 - 2s - loss: 0.5530 - accuracy: 0.7687
Epoch 156/250
935/935 - 2s - loss: 0.5527 - accuracy: 0.7690
Epoch 157/250
935/935 - 3s - loss: 0.5522 - accuracy: 0.7696
Epoch 158/250
935/935 - 2s - loss: 0.5526 - accuracy: 0.7680
Epoch 159/250
935/935 - 2s - loss: 0.5511 - accuracy: 0.7698
Epoch 160/250
935/935 - 2s - loss: 0.5522 - accuracy: 0.7688
Epoch 161/250
935/935 - 3s - loss: 0.5507 - accuracy: 0.7692
Epoch 162/250
935/935 - 2s - loss: 0.5503 - accuracy: 0.7699
Epoch 163/250
935/935 - 1s - loss: 0.5510 - accuracy: 0.7693
Epoch 164/250
935/935 - 1s - loss: 0.5501 - accuracy: 0.7703
Epoch 165/250
935/935 - 1s - loss: 0.5496 - accuracy: 0.7696
Epoch 166/250
935/935 - 1s - loss: 0.5498 - accuracy: 0.7695
Epoch 167/250
935/935 - 2s - loss: 0.5498 - accuracy: 0.7702
Epoch 168/250
935/935 - 2s - loss: 0.5492 - accuracy: 0.7697
Epoch 169/250
935/935 - 1s - loss: 0.5488 - accuracy: 0.7695
Epoch 170/250
935/935 - 2s - loss: 0.5485 - accuracy: 0.7701
Epoch 171/250
935/935 - 1s - loss: 0.5492 - accuracy: 0.7711
Epoch 172/250
935/935 - 2s - loss: 0.5480 - accuracy: 0.7712
Epoch 173/250
935/935 - 2s - loss: 0.5476 - accuracy: 0.7711
Epoch 174/250
935/935 - 2s - loss: 0.5474 - accuracy: 0.7711
Epoch 175/250
935/935 - 2s - loss: 0.5464 - accuracy: 0.7710
Epoch 176/250
935/935 - 2s - loss: 0.5464 - accuracy: 0.7707
Epoch 177/250
935/935 - 2s - loss: 0.5463 - accuracy: 0.7722
Epoch 178/250
935/935 - 2s - loss: 0.5458 - accuracy: 0.7715
Epoch 179/250
935/935 - 2s - loss: 0.5462 - accuracy: 0.7712
Epoch 180/250
935/935 - 2s - loss: 0.5451 - accuracy: 0.7717
Epoch 181/250
935/935 - 2s - loss: 0.5451 - accuracy: 0.7722
Epoch 182/250
935/935 - 2s - loss: 0.5458 - accuracy: 0.7711
Epoch 183/250
935/935 - 2s - loss: 0.5456 - accuracy: 0.7719
Epoch 184/250
935/935 - 2s - loss: 0.5443 - accuracy: 0.7712
Epoch 185/250
935/935 - 3s - loss: 0.5443 - accuracy: 0.7723
Epoch 186/250
935/935 - 3s - loss: 0.5448 - accuracy: 0.7721
Epoch 187/250
935/935 - 2s - loss: 0.5438 - accuracy: 0.7717
Epoch 188/250
935/935 - 1s - loss: 0.5448 - accuracy: 0.7724
Epoch 189/250
935/935 - 2s - loss: 0.5435 - accuracy: 0.7720
Epoch 190/250
935/935 - 1s - loss: 0.5424 - accuracy: 0.7725
Epoch 191/250
935/935 - 1s - loss: 0.5422 - accuracy: 0.7737
Epoch 192/250
935/935 - 2s - loss: 0.5434 - accuracy: 0.7718
Epoch 193/250
935/935 - 2s - loss: 0.5429 - accuracy: 0.7716
Epoch 194/250
935/935 - 2s - loss: 0.5419 - accuracy: 0.7734
Epoch 195/250
935/935 - 2s - loss: 0.5416 - accuracy: 0.7718
Epoch 196/250
935/935 - 2s - loss: 0.5422 - accuracy: 0.7721
Epoch 197/250
935/935 - 1s - loss: 0.5419 - accuracy: 0.7740
Epoch 198/250
935/935 - 1s - loss: 0.5421 - accuracy: 0.7739
Epoch 199/250
935/935 - 1s - loss: 0.5419 - accuracy: 0.7729
Epoch 200/250
935/935 - 1s - loss: 0.5409 - accuracy: 0.7737
Epoch 201/250
935/935 - 1s - loss: 0.5401 - accuracy: 0.7736
Epoch 202/250
935/935 - 1s - loss: 0.5401 - accuracy: 0.7728
Epoch 203/250
935/935 - 1s - loss: 0.5406 - accuracy: 0.7732
Epoch 204/250
935/935 - 1s - loss: 0.5409 - accuracy: 0.7729
Epoch 205/250
935/935 - 1s - loss: 0.5401 - accuracy: 0.7739
Epoch 206/250
935/935 - 1s - loss: 0.5408 - accuracy: 0.7738
Epoch 207/250
935/935 - 1s - loss: 0.5387 - accuracy: 0.7736
Epoch 208/250
935/935 - 1s - loss: 0.5400 - accuracy: 0.7732
Epoch 209/250
935/935 - 1s - loss: 0.5387 - accuracy: 0.7742
Epoch 210/250
935/935 - 2s - loss: 0.5387 - accuracy: 0.7736
Epoch 211/250
935/935 - 1s - loss: 0.5381 - accuracy: 0.7746
Epoch 212/250
935/935 - 1s - loss: 0.5379 - accuracy: 0.7744
Epoch 213/250
935/935 - 1s - loss: 0.5387 - accuracy: 0.7746
Epoch 214/250
935/935 - 1s - loss: 0.5380 - accuracy: 0.7737
Epoch 215/250
935/935 - 2s - loss: 0.5369 - accuracy: 0.7752
Epoch 216/250
935/935 - 2s - loss: 0.5387 - accuracy: 0.7742
Epoch 217/250
935/935 - 1s - loss: 0.5379 - accuracy: 0.7746
Epoch 218/250
935/935 - 1s - loss: 0.5377 - accuracy: 0.7737
Epoch 219/250
935/935 - 1s - loss: 0.5375 - accuracy: 0.7735
Epoch 220/250
935/935 - 1s - loss: 0.5367 - accuracy: 0.7748
Epoch 221/250
935/935 - 1s - loss: 0.5372 - accuracy: 0.7745
Epoch 222/250
935/935 - 1s - loss: 0.5355 - accuracy: 0.7747
Epoch 223/250
935/935 - 2s - loss: 0.5361 - accuracy: 0.7756
Epoch 224/250
935/935 - 1s - loss: 0.5358 - accuracy: 0.7744
Epoch 225/250
935/935 - 1s - loss: 0.5356 - accuracy: 0.7758
Epoch 226/250
935/935 - 2s - loss: 0.5367 - accuracy: 0.7735
Epoch 227/250
935/935 - 2s - loss: 0.5356 - accuracy: 0.7758
Epoch 228/250
935/935 - 2s - loss: 0.5350 - accuracy: 0.7749
Epoch 229/250
935/935 - 3s - loss: 0.5350 - accuracy: 0.7748
Epoch 230/250
935/935 - 2s - loss: 0.5339 - accuracy: 0.7754
Epoch 231/250
935/935 - 1s - loss: 0.5361 - accuracy: 0.7745
Epoch 232/250
935/935 - 2s - loss: 0.5358 - accuracy: 0.7757
Epoch 233/250
935/935 - 1s - loss: 0.5341 - accuracy: 0.7753
Epoch 234/250
935/935 - 2s - loss: 0.5338 - accuracy: 0.7762
Epoch 235/250
935/935 - 1s - loss: 0.5340 - accuracy: 0.7752
Epoch 236/250
935/935 - 1s - loss: 0.5335 - accuracy: 0.7759
Epoch 237/250
935/935 - 2s - loss: 0.5339 - accuracy: 0.7767
Epoch 238/250
935/935 - 3s - loss: 0.5347 - accuracy: 0.7754
Epoch 239/250
935/935 - 3s - loss: 0.5338 - accuracy: 0.7763
Epoch 240/250
935/935 - 2s - loss: 0.5327 - accuracy: 0.7761
Epoch 241/250
935/935 - 2s - loss: 0.5329 - accuracy: 0.7761
Epoch 242/250
935/935 - 2s - loss: 0.5336 - accuracy: 0.7762
Epoch 243/250
935/935 - 2s - loss: 0.5324 - accuracy: 0.7759
Epoch 244/250
935/935 - 2s - loss: 0.5326 - accuracy: 0.7761
Epoch 245/250
935/935 - 2s - loss: 0.5319 - accuracy: 0.7759
Epoch 246/250
935/935 - 2s - loss: 0.5311 - accuracy: 0.7760
Epoch 247/250
935/935 - 2s - loss: 0.5310 - accuracy: 0.7774
Epoch 248/250
935/935 - 2s - loss: 0.5322 - accuracy: 0.7768
Epoch 249/250
935/935 - 2s - loss: 0.5318 - accuracy: 0.7765
Epoch 250/250
935/935 - 2s - loss: 0.5320 - accuracy: 0.7769

Of the models, the neural network performed best with about 77% accuracy.  Overall, Abundance seems to be a difficult variable to predict - there may not be a strong correlation between it and the other variables.