In [1]:
#imports
import pandas as pd
import numpy as np

In [2]:
#csv -> dataframe
species_df = pd.read_csv('species.csv', dtype = str)
parks_df = pd.read_csv('parks.csv')

In [3]:
species_df.head()
#Note: not sure why there is a 14th data column showing-there are only 13 columns of data-this is confirmed
#in the documentation for the dataset. Will come back and drop that.

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [4]:
parks_df.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

In [5]:
#drop that extra column in species_df
species_df = species_df.iloc[: , :-1]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [6]:
#what are the possible labels for the "Record Status" column?
species_df["Record Status"].value_counts()

Approved                86254
In Review               32937
None                        6
 Chico                      1
 Whortleberry               1
 Leather Flower             1
 Willowherb                 1
 Liver Leaf*                1
 Bushtit                    1
 Golden Pea                 1
 Kinnikinnick               1
 Fringed Sage               1
 Shadbush                   1
 Common Poorwill            1
 Ground Daisy               1
 Downy Chess                1
 Common Mullein             1
 Robin                      1
 Claret Cup                 1
 Purple Cockle              1
 Clover Bush                1
 Speckled Trout             1
 Filaree                    1
 Cabezon                    1
 Wiregrass                  1
 Rushpink                   1
 Cranesbill                 1
 Manati                     1
 Northern Pintail           1
 Short-Tailed Weasel        1
 Skyrocket Gilia            1
 Northern Goshawk           1
 Osha                       1
 Cocodrilo De Tumbes        1
 Verdolagas                 1
 Wapiti                     1
 Wild Rose                  1
 Ranchers' Fireweed         1
 Dames Rocket               1
 White-Footed Mouse         1
 Goosefoot                  1
 Grass-Leaf Loco            1
 Catbird                    1
 Cenizo                     1
 Devil's Shoelaces          1
 American Crow              1
 Storksbill                 1
 Skunkbush                  1
 Speedwell                  1
P.Nut Sedge                 1
 *                          1
 Pigeon Hawk                1
 Bluebell                   1
 Wild Iris                  1
Name: Record Status, dtype: int64

In [8]:
#entries where "Record Status" is a Common Name clearly have errors
#entries with "In Review" record status are missing data in some fields,
#may not be as reliable as "Approved" entries
#BUT they make up a substantial portion of the dataset - let's try keeping them in

#keep only "Approved" entries
species_df_app = species_df[species_df['Record Status'].isin(["Approved", "In Review"])]
species_df_app

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [9]:
#this data is primarily text
#so we will need to do some label encoding before we can create and train data models

#label encode Park Name
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()
species_df_app['Park Name']=class_labels.fit_transform(species_df_app['Park Name'].values)
species_df_app

<ipython-input-9-cc308fe215cd>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Park Name']=class_labels.fit_transform(species_df_app['Park Name'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [10]:
#label encode Category
species_df_app['Category']=class_labels.fit_transform(species_df_app['Category'].values)
species_df_app

<ipython-input-10-7375de13e785>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Category']=class_labels.fit_transform(species_df_app['Category'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [11]:
#label encode Order
species_df_app['Order']=class_labels.fit_transform(species_df_app['Order'].values)
species_df_app

<ipython-input-11-f66aecc8b92b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Order']=class_labels.fit_transform(species_df_app['Order'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,41,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,87,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,87,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,87,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,546,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,546,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,553,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,553,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [12]:
#label encode Family
species_df_app['Family']=class_labels.fit_transform(species_df_app['Family'].values)
species_df_app

<ipython-input-12-a4fb3ffa2e1c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Family']=class_labels.fit_transform(species_df_app['Family'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,417,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [13]:
#label encode Occurrence
species_df_app['Occurrence']=class_labels.fit_transform(species_df_app['Occurrence'].values)
species_df_app

<ipython-input-13-7bb0a7fb4812>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Occurrence']=class_labels.fit_transform(species_df_app['Occurrence'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,417,Alces alces,Moose,Approved,4,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,4,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,4,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,4,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,Uncommon,NaN,NaN

In [14]:
#label encode Abundance
species_df_app['Abundance']=class_labels.fit_transform(species_df_app['Abundance'].values)
species_df_app

<ipython-input-14-46c1903612ac>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Abundance']=class_labels.fit_transform(species_df_app['Abundance'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,417,Alces alces,Moose,Approved,4,Native,3,Resident,NaN
1,ACAD-1001,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,NaN,NaN
2,ACAD-1002,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,NaN,Species of Concern
3,ACAD-1003,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,NaN,Endangered
4,ACAD-1004,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,NaN,NaN
119244,ZION-2792,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,4,Native,4,NaN,NaN
119245,ZION-2793,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,NaN,NaN
119246,ZION-2794,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,4,Native,3,NaN,NaN
119247,ZION-2795,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,NaN,NaN

In [15]:
#label encode Seasonality
species_df_app['Seasonality']=class_labels.fit_transform(species_df_app['Seasonality'].values)
species_df_app

<ipython-input-15-0dcda0641baf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Seasonality']=class_labels.fit_transform(species_df_app['Seasonality'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,417,Alces alces,Moose,Approved,4,Native,3,12,NaN
1,ACAD-1001,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,NaN
2,ACAD-1002,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,Species of Concern
3,ACAD-1003,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,Endangered
4,ACAD-1004,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,NaN
119244,ZION-2792,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,NaN
119245,ZION-2793,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,NaN
119246,ZION-2794,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,NaN
119247,ZION-2795,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,NaN

In [16]:
#label encode Conservation Status
species_df_app['Conservation Status']=class_labels.fit_transform(species_df_app['Conservation Status'].values)
species_df_app

<ipython-input-16-db17e04b9169>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Conservation Status']=class_labels.fit_transform(species_df_app['Conservation Status'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,41,417,Alces alces,Moose,Approved,4,Native,3,12,8
1,ACAD-1001,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,8
2,ACAD-1002,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,5
3,ACAD-1003,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,0
4,ACAD-1004,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,8
119244,ZION-2792,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,8
119245,ZION-2793,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,8
119246,ZION-2794,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,8
119247,ZION-2795,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,8

In [17]:
#label encode Species ID
species_df_app['Species ID']=class_labels.fit_transform(species_df_app['Species ID'].values)
species_df_app

<ipython-input-17-d87960d4782a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Species ID']=class_labels.fit_transform(species_df_app['Species ID'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,Alces alces,Moose,Approved,4,Native,3,12,8
1,1,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,8
2,2,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,5
3,3,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,0
4,4,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,119186,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,8
119244,119187,55,13,546,2301,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,8
119245,119188,55,13,546,2301,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,8
119246,119189,55,13,553,2331,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,8
119247,119190,55,13,553,2331,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,8

In [18]:
#label encode Record Status
species_df_app['Record Status']=class_labels.fit_transform(species_df_app['Record Status'].values)
species_df_app

<ipython-input-18-035c80616dda>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Record Status']=class_labels.fit_transform(species_df_app['Record Status'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,Alces alces,Moose,0,4,Native,3,12,8
1,1,0,8,41,417,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",0,4,Native,0,20,8
2,2,0,8,87,352,Canis latrans,"Coyote, Eastern Coyote",0,4,Not Native,1,20,5
3,3,0,8,87,352,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",0,0,Native,6,20,0
4,4,0,8,87,352,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",0,4,Unknown,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,119186,55,13,474,2012,Solanum triflorum,Cut-Leaf Nightshade,0,4,Native,4,20,8
119244,119187,55,13,546,2301,Vitis arizonica,Canyon Grape,0,4,Native,4,20,8
119245,119188,55,13,546,2301,Vitis vinifera,Wine Grape,0,4,Not Native,4,20,8
119246,119189,55,13,553,2331,Larrea tridentata,Creosote Bush,0,4,Native,3,20,8
119247,119190,55,13,553,2331,Tribulus terrestris,Puncture Vine,0,4,Not Native,4,20,8

In [19]:
#scientific names should be unique - each entry already has unique identifier in "Species ID"
#common names are useful for humans but may just muddy the waters for machine learning/modeling

species_df_filtered = species_df_app.drop(labels = ["Scientific Name", "Common Names"], axis = 1)

In [20]:
species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,0,4,Native,3,12,8
1,1,0,8,41,417,0,4,Native,0,20,8
2,2,0,8,87,352,0,4,Not Native,1,20,5
3,3,0,8,87,352,0,0,Native,6,20,0
4,4,0,8,87,352,0,4,Unknown,1,0,8

In [21]:
#how many labels are in the Nativeness column + what are the labels?
species_df_filtered["Nativeness"].value_counts()

Native        75950
Not Native    11095
Unknown        7101
Name: Nativeness, dtype: int64

In [22]:
#label encode Nativeness
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()
species_df_filtered['Nativeness']=class_labels.fit_transform(species_df_filtered['Nativeness'].values)
species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,41,417,0,4,0,3,12,8
1,1,0,8,41,417,0,4,0,0,20,8
2,2,0,8,87,352,0,4,1,1,20,5
3,3,0,8,87,352,0,0,0,6,20,0
4,4,0,8,87,352,0,4,2,1,0,8

In [23]:
#check data types - see if our label encoding behaved
species_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119191 entries, 0 to 119247
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Species ID           119191 non-null  int64
 1   Park Name            119191 non-null  int64
 2   Category             119191 non-null  int64
 3   Order                119191 non-null  int64
 4   Family               119191 non-null  int64
 5   Record Status        119191 non-null  int64
 6   Occurrence           119191 non-null  int64
 7   Nativeness           119191 non-null  int64
 8   Abundance            119191 non-null  int64
 9   Seasonality          119191 non-null  int64
 10  Conservation Status  119191 non-null  int64
dtypes: int64(11)
memory usage: 10.9 MB

In [38]:
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_df_filtered.drop('Nativeness', axis=1)
y = species_df_filtered['Nativeness']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [39]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [40]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression_rev = LogisticRegression()
regression_rev.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [41]:
#check performance of regression model
regression_rev.fit(X_train, y_train)
y_pred = regression_rev.predict(X_test)
regression_rev.score(X_test, y_test)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8554889047359369

In [42]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_rev = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_rev)

0.5810679836971941

In [43]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [77]:
X = species_df_filtered.drop('Nativeness', axis=1)
y = species_df_filtered['Nativeness']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [78]:
dt_rev = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_rev.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [79]:
y_pred = dt_rev.predict(X_test)

In [80]:
dt_rev_score = accuracy_score(y_test, y_pred)
print(dt_rev_score)

0.8706321573891522

In [81]:
#check rmse
rmse_dt_rev = MSE(y_test, y_pred) ** (1/2)
print(rmse_dt_rev)

0.5149308105661266

In [82]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

#set seed
SEED = 42

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = SEED)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [83]:
rf_rev = RandomForestRegressor(n_estimators = 400, min_samples_leaf = 0.1, random_state = SEED)
rf_rev.fit(X_train, y_train)

RandomForestRegressor(min_samples_leaf=0.1, n_estimators=400, random_state=42)

In [84]:
y_pred = rf_rev.predict(X_test)

rmse_rf_rev = MSE(y_test, y_pred) ** (1/2)
print(rmse_rf_rev)

0.7122155044144471

In [54]:
#neural network imports
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [57]:
X = species_df_filtered.drop('Nativeness', axis=1)
y = species_df_filtered['Nativeness']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

number_features = X_train.shape[1]

In [72]:
#defining the model
model = Sequential()
model.add(Dense(100, activation='relu', kernel_initializer='he_normal', input_shape=(number_features,)))
model.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(4, activation='softmax'))

In [73]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [75]:
model.fit(X_train, y_train, epochs=100, batch_size=100, verbose=2)

Epoch 1/100
954/954 - 1s - loss: 0.2524 - accuracy: 0.9046
Epoch 2/100
954/954 - 1s - loss: 0.2530 - accuracy: 0.9043
Epoch 3/100
954/954 - 1s - loss: 0.2524 - accuracy: 0.9039
Epoch 4/100
954/954 - 1s - loss: 0.2524 - accuracy: 0.9039
Epoch 5/100
954/954 - 1s - loss: 0.2523 - accuracy: 0.9042
Epoch 6/100
954/954 - 1s - loss: 0.2519 - accuracy: 0.9039
Epoch 7/100
954/954 - 1s - loss: 0.2516 - accuracy: 0.9041
Epoch 8/100
954/954 - 1s - loss: 0.2516 - accuracy: 0.9043
Epoch 9/100
954/954 - 1s - loss: 0.2522 - accuracy: 0.9037
Epoch 10/100
954/954 - 2s - loss: 0.2514 - accuracy: 0.9039
Epoch 11/100
954/954 - 1s - loss: 0.2517 - accuracy: 0.9041
Epoch 12/100
954/954 - 2s - loss: 0.2521 - accuracy: 0.9038
Epoch 13/100
954/954 - 1s - loss: 0.2517 - accuracy: 0.9047
Epoch 14/100
954/954 - 2s - loss: 0.2509 - accuracy: 0.9043
Epoch 15/100
954/954 - 1s - loss: 0.2508 - accuracy: 0.9047
Epoch 16/100
954/954 - 2s - loss: 0.2511 - accuracy: 0.9042
Epoch 17/100
954/954 - 1s - loss: 0.2503 - accuracy: 0.9049
Epoch 18/100
954/954 - 2s - loss: 0.2513 - accuracy: 0.9039
Epoch 19/100
954/954 - 2s - loss: 0.2502 - accuracy: 0.9047
Epoch 20/100
954/954 - 1s - loss: 0.2500 - accuracy: 0.9050
Epoch 21/100
954/954 - 1s - loss: 0.2506 - accuracy: 0.9046
Epoch 22/100
954/954 - 2s - loss: 0.2498 - accuracy: 0.9049
Epoch 23/100
954/954 - 2s - loss: 0.2502 - accuracy: 0.9047
Epoch 24/100
954/954 - 2s - loss: 0.2498 - accuracy: 0.9048
Epoch 25/100
954/954 - 1s - loss: 0.2500 - accuracy: 0.9049
Epoch 26/100
954/954 - 1s - loss: 0.2500 - accuracy: 0.9044
Epoch 27/100
954/954 - 2s - loss: 0.2495 - accuracy: 0.9052
Epoch 28/100
954/954 - 2s - loss: 0.2500 - accuracy: 0.9046
Epoch 29/100
954/954 - 2s - loss: 0.2483 - accuracy: 0.9052
Epoch 30/100
954/954 - 1s - loss: 0.2491 - accuracy: 0.9046
Epoch 31/100
954/954 - 1s - loss: 0.2499 - accuracy: 0.9048
Epoch 32/100
954/954 - 1s - loss: 0.2494 - accuracy: 0.9045
Epoch 33/100
954/954 - 1s - loss: 0.2487 - accuracy: 0.9053
Epoch 34/100
954/954 - 1s - loss: 0.2495 - accuracy: 0.9050
Epoch 35/100
954/954 - 2s - loss: 0.2490 - accuracy: 0.9047
Epoch 36/100
954/954 - 2s - loss: 0.2484 - accuracy: 0.9052
Epoch 37/100
954/954 - 2s - loss: 0.2488 - accuracy: 0.9057
Epoch 38/100
954/954 - 3s - loss: 0.2483 - accuracy: 0.9053
Epoch 39/100
954/954 - 2s - loss: 0.2483 - accuracy: 0.9050
Epoch 40/100
954/954 - 1s - loss: 0.2478 - accuracy: 0.9054
Epoch 41/100
954/954 - 3s - loss: 0.2483 - accuracy: 0.9054
Epoch 42/100
954/954 - 2s - loss: 0.2483 - accuracy: 0.9052
Epoch 43/100
954/954 - 2s - loss: 0.2481 - accuracy: 0.9054
Epoch 44/100
954/954 - 5s - loss: 0.2474 - accuracy: 0.9053
Epoch 45/100
954/954 - 2s - loss: 0.2479 - accuracy: 0.9056
Epoch 46/100
954/954 - 2s - loss: 0.2481 - accuracy: 0.9047
Epoch 47/100
954/954 - 2s - loss: 0.2479 - accuracy: 0.9050
Epoch 48/100
954/954 - 2s - loss: 0.2471 - accuracy: 0.9055
Epoch 49/100
954/954 - 2s - loss: 0.2476 - accuracy: 0.9050
Epoch 50/100
954/954 - 2s - loss: 0.2468 - accuracy: 0.9060
Epoch 51/100
954/954 - 1s - loss: 0.2464 - accuracy: 0.9055
Epoch 52/100
954/954 - 1s - loss: 0.2471 - accuracy: 0.9054
Epoch 53/100
954/954 - 1s - loss: 0.2468 - accuracy: 0.9056
Epoch 54/100
954/954 - 2s - loss: 0.2470 - accuracy: 0.9060
Epoch 55/100
954/954 - 2s - loss: 0.2471 - accuracy: 0.9061
Epoch 56/100
954/954 - 1s - loss: 0.2469 - accuracy: 0.9056
Epoch 57/100
954/954 - 1s - loss: 0.2467 - accuracy: 0.9063
Epoch 58/100
954/954 - 1s - loss: 0.2460 - accuracy: 0.9055
Epoch 59/100
954/954 - 1s - loss: 0.2468 - accuracy: 0.9059
Epoch 60/100
954/954 - 1s - loss: 0.2463 - accuracy: 0.9060
Epoch 61/100
954/954 - 1s - loss: 0.2467 - accuracy: 0.9055
Epoch 62/100
954/954 - 1s - loss: 0.2465 - accuracy: 0.9061
Epoch 63/100
954/954 - 1s - loss: 0.2460 - accuracy: 0.9055
Epoch 64/100
954/954 - 1s - loss: 0.2461 - accuracy: 0.9060
Epoch 65/100
954/954 - 1s - loss: 0.2459 - accuracy: 0.9059
Epoch 66/100
954/954 - 2s - loss: 0.2454 - accuracy: 0.9064
Epoch 67/100
954/954 - 2s - loss: 0.2456 - accuracy: 0.9055
Epoch 68/100
954/954 - 2s - loss: 0.2459 - accuracy: 0.9063
Epoch 69/100
954/954 - 2s - loss: 0.2460 - accuracy: 0.9060
Epoch 70/100
954/954 - 2s - loss: 0.2455 - accuracy: 0.9058
Epoch 71/100
954/954 - 1s - loss: 0.2454 - accuracy: 0.9060
Epoch 72/100
954/954 - 1s - loss: 0.2461 - accuracy: 0.9057
Epoch 73/100
954/954 - 1s - loss: 0.2450 - accuracy: 0.9062
Epoch 74/100
954/954 - 1s - loss: 0.2446 - accuracy: 0.9061
Epoch 75/100
954/954 - 1s - loss: 0.2447 - accuracy: 0.9061
Epoch 76/100
954/954 - 1s - loss: 0.2452 - accuracy: 0.9057
Epoch 77/100
954/954 - 1s - loss: 0.2445 - accuracy: 0.9062
Epoch 78/100
954/954 - 1s - loss: 0.2452 - accuracy: 0.9062
Epoch 79/100
954/954 - 1s - loss: 0.2449 - accuracy: 0.9060
Epoch 80/100
954/954 - 1s - loss: 0.2448 - accuracy: 0.9059
Epoch 81/100
954/954 - 1s - loss: 0.2444 - accuracy: 0.9061
Epoch 82/100
954/954 - 1s - loss: 0.2444 - accuracy: 0.9064
Epoch 83/100
954/954 - 1s - loss: 0.2446 - accuracy: 0.9065
Epoch 84/100
954/954 - 1s - loss: 0.2440 - accuracy: 0.9064
Epoch 85/100
954/954 - 1s - loss: 0.2441 - accuracy: 0.9067
Epoch 86/100
954/954 - 1s - loss: 0.2440 - accuracy: 0.9068
Epoch 87/100
954/954 - 1s - loss: 0.2441 - accuracy: 0.9070
Epoch 88/100
954/954 - 1s - loss: 0.2434 - accuracy: 0.9060
Epoch 89/100
954/954 - 1s - loss: 0.2442 - accuracy: 0.9064
Epoch 90/100
954/954 - 1s - loss: 0.2433 - accuracy: 0.9063
Epoch 91/100
954/954 - 1s - loss: 0.2440 - accuracy: 0.9062
Epoch 92/100
954/954 - 1s - loss: 0.2438 - accuracy: 0.9063
Epoch 93/100
954/954 - 1s - loss: 0.2431 - accuracy: 0.9064
Epoch 94/100
954/954 - 2s - loss: 0.2443 - accuracy: 0.9069
Epoch 95/100
954/954 - 3s - loss: 0.2428 - accuracy: 0.9065
Epoch 96/100
954/954 - 1s - loss: 0.2429 - accuracy: 0.9068
Epoch 97/100
954/954 - 1s - loss: 0.2428 - accuracy: 0.9075
Epoch 98/100
954/954 - 1s - loss: 0.2436 - accuracy: 0.9070
Epoch 99/100
954/954 - 1s - loss: 0.2433 - accuracy: 0.9066
Epoch 100/100
954/954 - 3s - loss: 0.2431 - accuracy: 0.9065