In [1]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#csv -> dataframe
species_df = pd.read_csv('species.csv', dtype = str)
parks_df = pd.read_csv('parks.csv')

In [3]:
species_df.head()
#Note: not sure why there is a 14th data column showing-there are only 13 columns of data-this is confirmed
#in the documentation for the dataset. Will come back and drop that.

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [4]:
parks_df.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

In [5]:
#drop that extra column in species_df
species_df = species_df.iloc[: , :-1]
species_df

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [6]:
#what are the possible labels for the "Record Status" column?
species_df["Record Status"].value_counts()

Approved                86254
In Review               32937
None                        6
 Cocodrilo De Tumbes        1
 Wild Iris                  1
 Bushtit                    1
 Skunkbush                  1
 Short-Tailed Weasel        1
 Leather Flower             1
 Ranchers' Fireweed         1
 Liver Leaf*                1
 Common Poorwill            1
 Northern Goshawk           1
 Common Mullein             1
 White-Footed Mouse         1
 Verdolagas                 1
 Cenizo                     1
 Manati                     1
 Speckled Trout             1
 Clover Bush                1
 Bluebell                   1
 Robin                      1
 Cranesbill                 1
 Whortleberry               1
 Rushpink                   1
 Wapiti                     1
 Downy Chess                1
 American Crow              1
 Kinnikinnick               1
 Catbird                    1
 Osha                       1
 Grass-Leaf Loco            1
 Purple Cockle              1
 Wiregrass                  1
 Dames Rocket               1
 Shadbush                   1
 Devil's Shoelaces          1
 Ground Daisy               1
 Wild Rose                  1
 Golden Pea                 1
 Skyrocket Gilia            1
 Chico                      1
 Claret Cup                 1
 Fringed Sage               1
 Goosefoot                  1
 Speedwell                  1
 Pigeon Hawk                1
 Filaree                    1
 Storksbill                 1
 Cabezon                    1
 Northern Pintail           1
P.Nut Sedge                 1
 *                          1
 Willowherb                 1
Name: Record Status, dtype: int64

In [7]:
#entries where "Record Status" is a Common Name clearly have errors
#entries with "In Review" record status are missing data in some fields,
#may not be as reliable as "Approved" entries

#keep only "Approved" entries
species_df_app = species_df[species_df['Record Status'] == "Approved"]
species_df_app

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [8]:
#this data is primarily text
#so we will need to do some label encoding before we can create and train data models

#label encode Park Name
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()
species_df_app['Park Name']=class_labels.fit_transform(species_df_app['Park Name'].values)
species_df_app

<ipython-input-8-cc308fe215cd>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Park Name']=class_labels.fit_transform(species_df_app['Park Name'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [9]:
#label encode Category
species_df_app['Category']=class_labels.fit_transform(species_df_app['Category'].values)
species_df_app

<ipython-input-9-7375de13e785>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Category']=class_labels.fit_transform(species_df_app['Category'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [10]:
#label encode Order
species_df_app['Order']=class_labels.fit_transform(species_df_app['Order'].values)
species_df_app

<ipython-input-10-f66aecc8b92b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Order']=class_labels.fit_transform(species_df_app['Order'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,33,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,66,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,66,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,66,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,379,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,379,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,385,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,385,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [11]:
#label encode Family
species_df_app['Family']=class_labels.fit_transform(species_df_app['Family'].values)
species_df_app

<ipython-input-11-a4fb3ffa2e1c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Family']=class_labels.fit_transform(species_df_app['Family'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,280,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

In [12]:
#label encode Occurrence
species_df_app['Occurrence']=class_labels.fit_transform(species_df_app['Occurrence'].values)
species_df_app

<ipython-input-12-7bb0a7fb4812>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Occurrence']=class_labels.fit_transform(species_df_app['Occurrence'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,280,Alces alces,Moose,Approved,4,Native,Rare,Resident,NaN
1,ACAD-1001,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,Abundant,NaN,NaN
2,ACAD-1002,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,NaN,NaN,Endangered
4,ACAD-1004,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,Uncommon,NaN,NaN
119244,ZION-2792,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,4,Native,Uncommon,NaN,NaN
119245,ZION-2793,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,4,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,4,Native,Rare,NaN,NaN
119247,ZION-2795,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,Uncommon,NaN,NaN

In [13]:
#label encode Abundance
species_df_app['Abundance']=class_labels.fit_transform(species_df_app['Abundance'].values)
species_df_app

<ipython-input-13-46c1903612ac>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Abundance']=class_labels.fit_transform(species_df_app['Abundance'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,280,Alces alces,Moose,Approved,4,Native,3,Resident,NaN
1,ACAD-1001,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,NaN,NaN
2,ACAD-1002,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,NaN,Species of Concern
3,ACAD-1003,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,NaN,Endangered
4,ACAD-1004,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,NaN,NaN
119244,ZION-2792,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,4,Native,4,NaN,NaN
119245,ZION-2793,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,NaN,NaN
119246,ZION-2794,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,4,Native,3,NaN,NaN
119247,ZION-2795,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,NaN,NaN

In [14]:
#label encode Seasonality
species_df_app['Seasonality']=class_labels.fit_transform(species_df_app['Seasonality'].values)
species_df_app

<ipython-input-14-0dcda0641baf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Seasonality']=class_labels.fit_transform(species_df_app['Seasonality'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,280,Alces alces,Moose,Approved,4,Native,3,12,NaN
1,ACAD-1001,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,NaN
2,ACAD-1002,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,Species of Concern
3,ACAD-1003,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,Endangered
4,ACAD-1004,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,NaN
119244,ZION-2792,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,NaN
119245,ZION-2793,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,NaN
119246,ZION-2794,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,NaN
119247,ZION-2795,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,NaN

In [15]:
#label encode Conservation Status
species_df_app['Conservation Status']=class_labels.fit_transform(species_df_app['Conservation Status'].values)
species_df_app

<ipython-input-15-db17e04b9169>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Conservation Status']=class_labels.fit_transform(species_df_app['Conservation Status'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,ACAD-1000,0,8,33,280,Alces alces,Moose,Approved,4,Native,3,12,8
1,ACAD-1001,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,8
2,ACAD-1002,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,5
3,ACAD-1003,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,0
4,ACAD-1004,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,8
119244,ZION-2792,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,8
119245,ZION-2793,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,8
119246,ZION-2794,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,8
119247,ZION-2795,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,8

In [16]:
#label encode Species ID
species_df_app['Species ID']=class_labels.fit_transform(species_df_app['Species ID'].values)
species_df_app

<ipython-input-16-d87960d4782a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df_app['Species ID']=class_labels.fit_transform(species_df_app['Species ID'].values)

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,33,280,Alces alces,Moose,Approved,4,Native,3,12,8
1,1,0,8,33,280,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,4,Native,0,20,8
2,2,0,8,66,234,Canis latrans,"Coyote, Eastern Coyote",Approved,4,Not Native,1,20,5
3,3,0,8,66,234,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,0,Native,6,20,0
4,4,0,8,66,234,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,4,Unknown,1,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,86249,55,13,335,1321,Solanum triflorum,Cut-Leaf Nightshade,Approved,4,Native,4,20,8
119244,86250,55,13,379,1507,Vitis arizonica,Canyon Grape,Approved,4,Native,4,20,8
119245,86251,55,13,379,1507,Vitis vinifera,Wine Grape,Approved,4,Not Native,4,20,8
119246,86252,55,13,385,1528,Larrea tridentata,Creosote Bush,Approved,4,Native,3,20,8
119247,86253,55,13,385,1528,Tribulus terrestris,Puncture Vine,Approved,4,Not Native,4,20,8

In [17]:
#scientific names should be unique - each entry already has unique identifier in "Species ID"
#common names are useful for humans but may just muddy the waters for machine learning/modeling
#all remaining entries should have Record Status of "Approved" - this column can also be dropped

species_df_filtered = species_df_app.drop(labels = ["Scientific Name", "Common Names", "Record Status"], axis = 1)

In [18]:
species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,33,280,4,Native,3,12,8
1,1,0,8,33,280,4,Native,0,20,8
2,2,0,8,66,234,4,Not Native,1,20,5
3,3,0,8,66,234,0,Native,6,20,0
4,4,0,8,66,234,4,Unknown,1,0,8

In [19]:
#how many labels are in the Nativeness column + what are the labels?
species_df_filtered["Nativeness"].value_counts()

Native        71235
Not Native    10510
Unknown        4509
Name: Nativeness, dtype: int64

In [20]:
#label encode Nativeness
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()
species_df_filtered['Nativeness']=class_labels.fit_transform(species_df_filtered['Nativeness'].values)
species_df_filtered.head()

,Species ID,Park Name,Category,Order,Family,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status
0,0,0,8,33,280,4,0,3,12,8
1,1,0,8,33,280,4,0,0,20,8
2,2,0,8,66,234,4,1,1,20,5
3,3,0,8,66,234,0,0,6,20,0
4,4,0,8,66,234,4,2,1,0,8

In [21]:
#check data types - see if our label encoding behaved
species_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 86254 entries, 0 to 119247
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Species ID           86254 non-null  int64
 1   Park Name            86254 non-null  int64
 2   Category             86254 non-null  int64
 3   Order                86254 non-null  int64
 4   Family               86254 non-null  int64
 5   Occurrence           86254 non-null  int64
 6   Nativeness           86254 non-null  int64
 7   Abundance            86254 non-null  int64
 8   Seasonality          86254 non-null  int64
 9   Conservation Status  86254 non-null  int64
dtypes: int64(10)
memory usage: 7.2 MB

In [23]:
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_df_filtered.drop('Nativeness', axis=1)
y = species_df_filtered['Nativeness']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [24]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [25]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression = LogisticRegression()
regression.fit(X_train, y_train)

LogisticRegression()

In [26]:
#check performance of regression model
regression.fit(X_train, y_train)
y_pred = regression.predict(X_test)
regression.score(X_test, y_test)

0.8360423864400491