# Biodiversity in US National Parks

## Coder Girl 2021 Data Science Final Project

### Chrissy Bellizzi and Jenny Arbuszewski

# Executive Summary

## Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#defining a function to read our csv files and create dataframes
def read_csv(file, data_type = None):
    df_name = pd.read_csv(file, dtype = data_type)
    return df_name

species_df = read_csv('species.csv', str)
species_df.head()

#This is honestly faster to NOT use a function.

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [3]:
parks_df = read_csv('parks.csv')
parks_df.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

# Preprocessing

## Renaming Columns to eliminate spaces

In [4]:
species_df.rename(columns = {'Species ID':'Species_ID'}, inplace = True)

species_df.rename(columns = {'Park Name':'Park_name'}, inplace = True)

species_df.rename(columns = {'Scientific Name':'Scientific_name'}, inplace = True)

species_df.rename(columns = {'Common Names':'Common_name'}, inplace = True)

species_df.rename(columns = {'Record Status':'Record_status'}, inplace = True)

species_df.rename(columns = {'Conservation Status':'Conservation_status'}, inplace = True)
species_df

,Species_ID,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN,NaN

In [5]:
#removing spaces for park code and park name

parks_df.rename(columns = {'Park Code':'Park_code'}, inplace = True)

parks_df.rename(columns = {'Park Name':'Park_name'}, inplace = True)

parks_df.head()

  Park_code               Park_name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

## Removing Empty column

In [6]:
species_df.head()
#Note: not sure why there is a 14th data column showing-there are only 13 columns of data-this is confirmed
#in the documentation for the dataset. Will come back and drop that.

,Species_ID,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [7]:
#drop that extra column in species_df
species_df = species_df.iloc[: , :-1]
species_df

,Species_ID,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,ZION-2791,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,ZION-2792,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,ZION-2793,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,ZION-2794,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,ZION-2795,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

### Dropping the species_id column

This column is somewhat redundant. We can essentially get the same information by combining the park name and scientific name so it will be removed from our primary dataframe.

In [8]:
species_df= species_df.drop(['Species_ID'], axis=1)
species_df

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern
3,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,NaN,NaN
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,NaN,NaN
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,NaN,NaN
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,NaN,NaN
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,NaN,NaN

### Creating a new column for Plant/Animal Boolean

We wanted a simple way to filter by whether or not the organism in question was a plant or an animal. We recognize that fungi do not belong to either designation but for simplicity and ease of calculations, here we include all fungi in the plant category

In [9]:
plant_animal_boolean_list = []
for entry in species_df['Category']:
    if entry == 'Vascular Plant' or  entry =='Fungi' or entry =='Nonvascular Plant' or entry =='Algae':
        plant_animal_boolean = 0
        plant_animal_boolean_list.append(plant_animal_boolean)
    else:
        plant_animal_boolean = 1
        plant_animal_boolean_list.append(plant_animal_boolean)

species_df['plant_animal_boolean'] = plant_animal_boolean_list

species_df.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,1
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,1
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,1
3,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,1

### Looking at the values and number of unique entries for most categories

In [10]:
def unique(dataframe, column):
    print('The unique categories and number of values for ' + column + ' are: ')
    print(dataframe[str(column)].unique())
    print(dataframe[str(column)].nunique())

unique(species_df, 'Category')

The unique categories and number of values for Category are:
['Mammal' 'Bird' 'Reptile' 'Amphibian' 'Fish' 'Vascular Plant'
 'Spider/Scorpion' 'Insect' 'Invertebrate' 'Fungi' 'Nonvascular Plant'
 'Crab/Lobster/Shrimp' 'Slug/Snail' 'Algae']
14

In [11]:
unique(species_df, 'Park_name')

The unique categories and number of values for Park_name are:
['Acadia National Park' 'Arches National Park' 'Badlands National Park'
 'Big Bend National Park' 'Biscayne National Park'
 'Black Canyon of the Gunnison National Park' 'Bryce Canyon National Park'
 'Canyonlands National Park' 'Capitol Reef National Park'
 'Carlsbad Caverns National Park' 'Channel Islands National Park'
 'Congaree National Park' 'Crater Lake National Park'
 'Cuyahoga Valley National Park' 'Denali National Park and Preserve'
 'Death Valley National Park' 'Dry Tortugas National Park'
 'Everglades National Park'
 'Gates Of The Arctic National Park and Preserve' 'Glacier National Park'
 'Glacier Bay National Park and Preserve' 'Great Basin National Park'
 'Grand Canyon National Park'
 'Great Sand Dunes National Park and Preserve'
 'Great Smoky Mountains National Park' 'Grand Teton National Park'
 'Guadalupe Mountains National Park' 'Haleakala National Park'
 'Hawaii Volcanoes National Park' 'Hot Springs National Park'
 'Isle Royale National Park' 'Joshua Tree National Park'
 'Katmai National Park and Preserve' 'Kenai Fjords National Park'
 'Kobuk Valley National Park' 'Lake Clark National Park and Preserve'
 'Lassen Volcanic National Park' 'Mammoth Cave National Park'
 'Mesa Verde National Park' 'Mount Rainier National Park'
 'North Cascades National Park' 'Olympic National Park'
 'Petrified Forest National Park' 'Pinnacles National Park'
 'Redwood National Park' 'Rocky Mountain National Park'
 'Saguaro National Park' 'Sequoia and Kings Canyon National Parks'
 'Shenandoah National Park' 'Theodore Roosevelt National Park'
 'Voyageurs National Park' 'Wind Cave National Park'
 'Wrangell - St Elias National Park and Preserve'
 'Yellowstone National Park' 'Yosemite National Park' 'Zion National Park']
56

In [12]:
unique(species_df, 'Order')

The unique categories and number of values for Order are:
['Artiodactyla' 'Carnivora' 'Chiroptera' 'Lagomorpha' 'Rodentia'
 'Soricomorpha' 'Accipitriformes' 'Anseriformes' 'Apodiformes'
 'Caprimulgiformes' 'Charadriiformes' 'Columbiformes' 'Coraciiformes'
 'Cuculiformes' 'Falconiformes' 'Galliformes' 'Gaviiformes' 'Gruiformes'
 'Passeriformes' 'Pelecaniformes' 'Piciformes' 'Podicipediformes'
 'Procellariiformes' 'Strigiformes' 'Suliformes' 'Squamata' 'Testudines'
 'Anura' 'Caudata' 'Anguilliformes' 'Atheriniformes' 'Clupeiformes'
 'Cypriniformes' 'Cyprinodontiformes' 'Esociformes' 'Gadiformes'
 'Gasterosteiformes' 'Osmeriformes' 'Perciformes' 'Pleuronectiformes'
 'Salmoniformes' 'Siluriformes' nan 'Acorales' 'Alismatales' 'Apiales'
 'Aquifoliales' 'Asparagales' 'Asterales' 'Boraginales' 'Brassicales'
 'Caryophyllales' 'Celastrales' 'Ceratophyllales' 'Commelinales'
 'Cornales' 'Cucurbitales' 'Dipsacales' 'Equisetales' 'Ericales' 'Fabales'
 'Fagales' 'Gentianales' 'Geraniales' 'Isoetales' 'Lamiales' 'Liliales'
 'Lycopodiales' 'Malpighiales' 'Malvales' 'Myrtales' 'Nymphaeales'
 'Ophioglossales' 'Osmundales' 'Oxalidales' 'Pinales' 'Piperales' 'Poales'
 'Polypodiales' 'Ranunculales' 'Rosales' 'Santalales' 'Sapindales'
 'Saxifragales' 'Selaginellales' 'Solanales' 'Vitales' 'Ephedrales'
 'Zygophyllales' 'Perissodactyla' 'Osteoglossiformes' 'Araneae'
 'Coleoptera' 'Diptera' 'Hemiptera' 'Hymenoptera' 'Lepidoptera'
 'Orthoptera' 'Stauromedusae' 'Acarosporales' 'Agyriales' 'Arthoniales'
 'Candelariales' 'Lecanorales' 'Lichinales' 'Ostropales' 'Peltigerales'
 'Pertusariales' 'Rhizocarpales' 'Teloschistales' 'Umbilicariales'
 'Verrucariales' 'Didelphimorphia' 'Trogoniformes' 'Acipenseriformes'
 'Characiformes' 'Semionotiformes' 'Arecales' 'Crossosomatales'
 'Garryales' 'Schizaeales' 'Bartramiales' 'Bryales' 'Dicranales'
 'Funariales' 'Grimmiales' 'Hedwigiales' 'Hypnales' 'Orthotrichales'
 'Pottiales' 'Cetacea' 'Sirenia' 'Ciconiiformes' 'Phaethontiformes'
 'Phoenicopteriformes' 'Crocodilia' 'Albuliformes' 'Amiiformes'
 'Aulopiformes' 'Batrachoidiformes' 'Beloniformes' 'Beryciformes'
 'Carcharhiniformes' 'Elopiformes' 'Lampridiformes' 'Lophiiformes'
 'Mugiliformes' 'Myliobatiformes' 'Ophidiiformes' 'Orectolobiformes'
 'Percopsiformes' 'Pristiformes' 'Rajiformes' 'Rhinobatiformes'
 'Scorpaeniformes' 'Squaliformes' 'Stomiiformes' 'Tetraodontiformes'
 'Torpediniformes' 'Canellales' 'Cycadales' 'Laurales' 'Magnoliales'
 'Psilotales' 'Zingiberales' 'Anthoathecatae' 'Scleractinia' 'Salviniales'
 'Cingulata' 'Chimaeriformes' 'Heterodontiformes' 'Lamniformes'
 'Myctophiformes' 'Myxiniformes' 'Squatiniformes' 'Proteales'
 'Acrochaetiales' 'Ahnfeltiales' 'Bangiales' 'Bonnemaisoniales'
 'Bryopsidales' 'Ceramiales' 'Cladophorales' 'Corallinales' 'Gelidiales'
 'Gigartinales' 'Rhodymeniales' 'Ulvales' 'Amphipoda' 'Decapoda'
 'Pedunculata' 'Sessilia' 'Archaeogastropoda' 'Basommatophora'
 'Neogastropoda' 'Neotaenioglossa' 'Patellogastropoda'
 'Systellommatophora' 'Mesostigmata' 'Actiniaria' 'Amphioxiformes'
 'Apodida' 'Arbacioida' 'Aspidochirotida' 'Canalipalpata' 'Cheilostomata'
 'Chitonida' 'Clathrinida' 'Clypeasteroida' 'Cyclostomata'
 'Dendrochirotida' 'Diadematoida' 'Echinoida' 'Enterogona' 'Forcipulatida'
 'Limoida' 'Lingulida' 'Molpadiida' 'Myoida' 'Mytiloida' 'Octopoda'
 'Ophiurida' 'Ostreoida' 'Paxillosida' 'Pholadomyoida' 'Pleurogona'
 'Pterioida' 'Pyrosomida' 'Salpida' 'Sepiolida' 'Solemyoida' 'Spatangoida'
 'Spinulosida' 'Temnopleuroida' 'Teuthida' 'Valvatida' 'Veneroida'
 'Cutleriales' 'Desmarestiales' 'Dictyosiphonales' 'Dictyotales'
 'Ectocarpales' 'Fucales' 'Laminariales' 'Scytosiphonales'
 'Sphacelariales' 'Sporochnales' 'Dioscoreales' 'Porellales'
 'Sphaeropleales' 'Sphagnales' 'Harpacticoida' 'Isopoda'
 'Architaenioglossa' 'Nudibranchia' 'Stylommatophora' 'Ephemeroptera'
 'Mantodea' 'Megaloptera' 'Odonata' 'Plecoptera' 'Trichoptera'
 'Arhynchobdellida' 'Collembola' 'Neoophora' 'Spirobolida' 'Tubificida'
 'Agaricales' 'Atractiellales' 'Auriculariales' 'Boletales'
 'Cantharellales' 'Capnodiales' 'Ceratiomyxales' 'Dacrymycetales'
 'Geastrales' 'Geoglossales' 'Helotiales' 'Hymenochaetales' 'Lecideales'
 'Leotiales' 'Liceales' 'Lycoperdales' 'Pezizales' 'Phallales'
 'Physarales' 'Polyporales' 'Pyrenulales' 'Russulales' 'Stemonitales'
 'Tremellales' 'Trichiales' 'Trypetheliales' 'Xylariales' 'Achnanthales'
 'Aulacoseirales' 'Bacillariales' 'Cymbellales' 'Eunotiales'
 'Fragilariales' 'Naviculales' 'Surirellales' 'Tabellariales'
 'Petromyzontiformes' 'Anthocerotales' 'Chaetosphaeridiales'
 'Chlamydomonadales' 'Chlorellales' 'Desmidiales' 'Encalyptales'
 'Glaucocystales' 'Jungermanniales' 'Marchantiales' 'Oedogoniales'
 'Pelliales' 'Polytrichales' 'Rhizogoniales' 'Splachnales' 'Ulotrichales'
 'Zygnematales' 'Anostraca' 'Bolelloid' 'Brandionus' 'Calanoida'
 'Cyclopoida' 'Diplostraca' 'Ostracoda' 'Podocopida' 'Ixodida' 'Opiliones'
 'Scorpiones' 'Archaeognatha' 'Blattodea' 'Homoptera' 'Mecoptera'
 'Neuroptera' 'Raphidioptera' 'Siphonaptera' 'Thysanoptera'
 'Collothecaceae' 'Copelata' 'Flosculariaceae' 'Gordioidea' 'Julida'
 'Lumbriculida' 'Parachela' 'Ploima' 'Polydesmida' 'Rhynchobdellida'
 'Cortinariales' 'Dothideales' 'Eumycota' 'Exobasidiales' 'Hypocreales'
 'Pleosporales' 'Pucciniales' 'Rhytismatales' 'Saprolegniales'
 'Taphrinales' 'Uredinales' 'Ustilaginales' 'Chromalinales'
 'Chrysocapsales' 'Coscinodiscales' 'Cryptomonadales' 'Gonyaulacales'
 'Gymnodiniales' 'Isochrysidales' 'Melosirales' 'Mischococcales'
 'Ochromonadales' 'Peridiniales' 'Prymnesiales' 'Rhizochloridales'
 'Rhopalodiales' 'Thalassiophysales' 'Thalassiosirales' 'Tribonematales'
 'Vaucheriales' 'Buxales' 'Heterostropha' 'Acari' 'Unionoida'
 'Ptilidiales' 'Timmiales' 'Pseudophyllidea' 'Primates' 'Psittaciformes'
 'Austrobaileyales' 'Batrachospermales' 'Charales' 'Klebsormidiales'
 'Notostraca' 'Mesogastropoda' 'Acariformes' 'Pseudoscorpiones'
 'Schizomida' 'Zygentoma' 'Callipodida' 'Rhabditida' 'Spirurida'
 'Strongylida' 'Baeomycetales' 'Eurotiales' 'Microascales' 'Mucorales'
 'Onygenales' 'Peronosporales' 'Sordariales' 'Trichosphaeriales'
 'Mastogloiales' 'Pandanales' 'Synbranchiformes' 'Hymenophyllales'
 'Picramniales' 'Andreaeales' 'Blasiales' 'Buxbaumiales' 'Fossombroniales'
 'Metzgeriales' 'Scouleriales' 'Tetraphidales' 'Hexanchiformes'
 'Stephanoberyciformes' 'Halymeniales' 'Palmariales' 'Peyssonneliales'
 'Plocamiales' 'Euphausiacea' 'Poecilostomatoida' 'Trombidiformes'
 'Alcyonacea' 'Halichondrida' 'Hydroida' 'Leptothecatae' 'Leucosolenida'
 'Paleonemertea' 'Pennatulacea' 'Phrynophiurida' 'Poecilosclerida'
 'Polycladida' 'Terebratulida' 'Velatida' 'Chaetophorales' 'Prasiolales'
 'Oribatida' 'Psocoptera' 'Chordeumatida' 'Gomphales' 'Solpugida'
 'Dendrocerotales' 'Hookeriales' 'Notothyladales' 'Pallaviciniales'
 'Phasmida' 'Apochela' 'Branchiobdellida' 'Diplura' 'Echiniscoidea'
 'Enchytraeida' 'Scolopendrida' 'Mycocaliciales' 'Erysiphales'
 'Cyatheales' 'Gleicheniales' 'Gunnerales' 'Huerteales' 'Marattiales'
 'Hildenbrandiales' 'Hypnodendrales' 'Neritopsina' 'Pseudoscorpionida'
 'Sarcoptiformes' 'Dermaptera' 'Embioptera' 'Psocodea' 'Haplosclerida'
 'Escalloniales' 'Tanaidacea' 'Anaspidea' 'Cephalaspidea' 'Notaspidea'
 'Strepsiptera' 'Arcoida' 'Astrophorida' 'Baerida' 'Chondrosida'
 'Cidaroida' 'Dictyoceratida' 'Echiurida' 'Eunicida' 'Hadromerida'
 'Heteronemertea' 'Hoplonemertea' 'Lithobiomorpha' 'Opisthopora'
 'Phyllodocida' 'Plagiorchiida' 'Scolecida' 'Spirostreptida' 'Zoantharia'
 'Saccharomycetales' 'Coleochaetales' 'Chaetocerotales' 'Chlorococcales'
 'Microthamniales' 'Solifugae' 'Ascaridida' 'Semaeostomeae'
 'Sipunculiformes' 'Oedipodiales' 'Plumatellida' 'Endogonales'
 'Bryoxiphiales' 'Grylloblattodea' 'Thelephorales' 'Mermithida'
 'Zeiformes' 'Cryptonemiales' 'Erythropeltidales' 'Nemastomatales'
 'Mysida' 'Podocopa' 'Odonates' 'Amphinomida' 'Corallimorpharia'
 'Ctenostomata' 'Cydippida' 'Echinorhynchida' 'Echinostomida'
 'Golfingiiformes' 'Haplotaxida' 'Opisthorchiida' 'Pantopoda'
 'Phascolosomatiformes' 'Solitaria' 'Strigeatida' 'Trachymedusae'
 'Botryosphaeriales' 'Chrysamoebidales' 'Rhizochrysidales' 'Tetrasporales'
 'Trebouxiales' 'Conchostraca' 'Cyclorhagida' 'Corticiales'
 'Echinostelliales' 'Neolectales' 'Pennales' 'Rhizosoleniales'
 'Ginkgoales' 'Sebacinales' 'Siphonostomatoida' 'Myxosporida'
 'Neoechinorhynchida']
554

In [13]:
unique(species_df, 'Family')

The unique categories and number of values for Family are:
['Cervidae' 'Canidae' 'Felidae' ... 'Pseudeurotiaceae'
 'Cunninghamellaceae' 'Saccharomycetaceae']
2332

In [14]:
unique(species_df, 'Scientific_name')

The unique categories and number of values for Scientific_name are:
['Alces alces' 'Odocoileus virginianus' 'Canis latrans' ...
 'Selaginella utahensis' 'Calystegia longipes'
 'Physalis hederifolia var. palmeri']
46022

In [15]:
unique(species_df, 'Category')

The unique categories and number of values for Category are:
['Mammal' 'Bird' 'Reptile' 'Amphibian' 'Fish' 'Vascular Plant'
 'Spider/Scorpion' 'Insect' 'Invertebrate' 'Fungi' 'Nonvascular Plant'
 'Crab/Lobster/Shrimp' 'Slug/Snail' 'Algae']
14

In [16]:
unique_states = parks_df['State'].unique()
print(unique_states)

num_unique_states = parks_df['State'].nunique()
print(num_unique_states)

['ME' 'UT' 'SD' 'TX' 'FL' 'CO' 'NM' 'CA' 'SC' 'OR' 'OH' 'AK' 'CA, NV' 'MT'
 'NV' 'AZ' 'TN, NC' 'WY' 'HI' 'AR' 'MI' 'KY' 'WA' 'VA' 'ND' 'MN'
 'WY, MT, ID']
27

### Considering basic information about size of parks

In [17]:
parks_df['Acres'].describe()

count    5.600000e+01
mean     9.279291e+05
std      1.709258e+06
min      5.550000e+03
25%      6.901050e+04
50%      2.387645e+05
75%      8.173602e+05
max      8.323148e+06
Name: Acres, dtype: float64

## First Pass -- missing data, data types, etc

### Seasonality

In [18]:
#what are the possible labels for the "Seasonality" column?
species_df["Seasonality"].value_counts()

Breeder                                 12214
Resident                                 3215
Migratory                                2825
Vagrant                                  1660
Breeder, Winter                            64
Rare                                       35
Summer                                     26
Migratory, Winter                          24
Breeder, Resident                          20
Winter                                     20
Breeder, Migratory                         13
Resident, Winter                            9
Uncommon                                    5
Common                                      4
Migratory, Vagrant                          4
Migratory, Summer                           3
Summer, Vagrant                             3
Unknown                                     3
Breeder, Resident, Summer                   3
Breeder, Summer                             2
Resident, Summer                            2
Breeder, Resident, Summer, Winter           1
Breeder, Resident, Migratory, Summer        1
Winter, Vagrant                             1
Name: Seasonality, dtype: int64

In [19]:
#need to retain Seasonality NaNs or we lose the Plants

new_seasons = []

for index, row in species_df.iterrows():
    if row['plant_animal_boolean'] == 1:
        if row['Seasonality'] == '' or row['Seasonality'] == 'NaN' or pd.isna(row['Seasonality']):
            new_seasons.append('Not_known')
        else:
            new_seasons.append(row['Seasonality'])
    else:
        new_seasons.append('Plant')
        
species_df['Seasonality'] = new_seasons

species_df

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,1
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,Not_known,NaN,1
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,Not_known,Species of Concern,1
3,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,Not_known,Endangered,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,Plant,NaN,0
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,Plant,NaN,0
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,Plant,NaN,0
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,Plant,NaN,0
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,Plant,NaN,0

In [20]:
#20 labels in "Seasonality"; several have only a few entries - outliers may skew data
#good amount of null values as well
#let's focus on four main "Seasonality" labels
#and Plants!

species_df = species_df[species_df['Seasonality'].isin(["Breeder", "Resident", "Vagrant", "Migratory", "Plant"])]
species_df

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,1
6,Acadia National Park,Mammal,Carnivora,Felidae,Lynx rufus,"Bay Lynx, Bobcat, Red Lynx, Wild Cat",Approved,Not Present (Historical Report),Not Native,NaN,Vagrant,NaN,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,Common,Breeder,NaN,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,Occasional,Migratory,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,Uncommon,Plant,NaN,0
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,Uncommon,Plant,NaN,0
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,Uncommon,Plant,NaN,0
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,Rare,Plant,NaN,0
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,Uncommon,Plant,NaN,0

### Abundance

In [21]:
#what are the possible labels for the "Abundance" column?
species_df["Abundance"].value_counts()

Unknown       23185
Uncommon      18383
Common        12611
Rare          10334
Occasional     3036
Abundant       2304
Native           27
Not Native        9
Name: Abundance, dtype: int64

In [22]:
#Remove Native and Not Native as those are clearly typos. Replace with 'Entry_error'

species_df.loc[(species_df.Abundance == 'Native'),'Abundance']='Entry_error'     
species_df.loc[(species_df.Abundance == 'Not Native'),'Abundance']='Entry_error'
species_df['Abundance'].value_counts()

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Unknown        23185
Uncommon       18383
Common         12611
Rare           10334
Occasional      3036
Abundant        2304
Entry_error       36
Name: Abundance, dtype: int64

### Handling NaNs

In [23]:
species_df.isnull().sum()

Park_name                   0
Category                    0
Order                     920
Family                    901
Scientific_name             0
Common_name                 0
Record_status               0
Occurrence              11271
Nativeness              13863
Abundance               26703
Seasonality                 0
Conservation_status     93099
plant_animal_boolean        0
dtype: int64

In [24]:
species_df.loc[(species_df.Conservation_status.isnull()),'Conservation_status']='None_given'
species_df.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,None_given,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,None_given,1
6,Acadia National Park,Mammal,Carnivora,Felidae,Lynx rufus,"Bay Lynx, Bobcat, Red Lynx, Wild Cat",Approved,Not Present (Historical Report),Not Native,NaN,Vagrant,None_given,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,Common,Breeder,None_given,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,Occasional,Migratory,None_given,1

In [25]:
species_df.dropna(subset = ["Abundance"], inplace=True)
species_df.dropna(subset = ["Nativeness"], inplace=True)

<ipython-input-25-5835c68ffb17>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df.dropna(subset = ["Abundance"], inplace=True)
<ipython-input-25-5835c68ffb17>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df.dropna(subset = ["Nativeness"], inplace=True)

In [26]:
species_df.isnull().sum()

Park_name                 0
Category                  0
Order                   274
Family                  270
Scientific_name           0
Common_name               0
Record_status             0
Occurrence                0
Nativeness                0
Abundance                 0
Seasonality               0
Conservation_status       0
plant_animal_boolean      0
dtype: int64

In [27]:
species_df.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,None_given,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,None_given,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,Common,Breeder,None_given,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,Occasional,Migratory,None_given,1
28,Acadia National Park,Mammal,Lagomorpha,Leporidae,Lepus americanus,"Snowshoe Hare, Varying Hare",Approved,Present,Native,Common,Breeder,None_given,1

#### Not dropping NaN for Order and Family because species names are present. If we need to drop for particular models later, we will.

### Making maps of park states, locations, number of parks per state, and biodiversity measures within parks.

In [28]:
#Considering number of species in a given park

#species_df.groupby(['Park_name']).count()

species_df.groupby(['Park_name']).nunique()

,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
Park_name,,,,,,,,,,,,
Acadia National Park,6,79,193,1112,1077,3,2,4,7,5,5,2
Arches National Park,6,57,144,719,714,1,1,2,6,5,5,2
Badlands National Park,5,59,136,647,644,3,2,4,7,5,6,2
Big Bend National Park,7,85,250,2003,1918,2,1,2,6,5,6,2
Biscayne National Park,5,76,192,787,768,2,1,2,5,5,5,2
Black Canyon of the Gunnison National Park,6,58,145,682,676,1,1,2,6,5,4,2
Bryce Canyon National Park,5,53,134,768,762,2,1,2,6,5,5,2
Canyonlands National Park,6,64,159,856,850,1,1,2,6,5,5,2
Capitol Reef National Park,6,64,173,1155,1149,1,1,3,6,5,5,2
Carlsbad Caverns National Park,6,66,172,1215,1204,2,1,2,3,5,6,2
Channel Islands National Park,6,85,232,1337,1305,1,1,2,6,5,6,2
Congaree National Park,4,69,197,1070,1028,2,1,3,6,5,5,2
Crater Lake National Park,6,56,138,1078,944,2,1,2,6,5,5,2
Cuyahoga Valley National Park,10,93,235,1581,1483,2,1,3,6,5,5,2
Death Valley National Park,6,69,178,1381,1335,3,2,4,7,5,6,2
Denali National Park and Preserve,5,55,128,962,892,1,1,3,6,4,3,2
Dry Tortugas National Park,5,53,124,443,435,2,1,3,6,5,6,2
Everglades National Park,6,110,331,1624,1570,2,1,3,6,5,7,2
Gates Of The Arctic National Park and Preserve,3,43,92,644,551,1,1,1,4,5,2,2
Glacier Bay National Park and Preserve,8,88,189,908,815,2,1,3,6,5,5,2
Glacier National Park,11,116,289,2216,1714,2,1,3,6,5,5,2
Grand Canyon National Park,9,45,113,536,492,1,1,3,6,5,6,2
Grand Teton National Park,6,68,176,1635,1462,4,2,4,7,5,5,2
Great Basin National Park,5,52,133,890,819,2,1,3,6,5,5,2
Great Sand Dunes National Park and Preserve,8,60,154,835,821,29,2,4,7,5,3,2
Great Smoky Mountains National Park,7,116,327,2519,2220,2,1,2,6,5,6,2
Guadalupe Mountains National Park,12,83,215,1387,1297,2,1,3,5,4,4,2
Haleakala National Park,13,130,464,2082,880,2,1,3,6,5,5,2
Hawaii Volcanoes National Park,13,165,544,2712,1002,1,1,3,6,5,6,2
Hot Springs National Park,8,77,176,598,559,2,1,3,6,4,4,2
Isle Royale National Park,7,77,181,1110,1100,2,1,3,6,5,6,2
Joshua Tree National Park,6,64,160,848,814,2,1,3,6,5,4,2
Katmai National Park and Preserve,7,63,132,731,664,2,1,3,6,5,5,2
Kenai Fjords National Park,5,53,118,561,541,1,1,3,6,5,5,2
Kobuk Valley National Park,3,41,85,458,411,1,1,1,6,4,2,2
Lake Clark National Park and Preserve,5,59,133,928,854,1,1,3,6,5,5,2
Lassen Volcanic National Park,7,62,157,987,956,2,1,3,6,5,5,2
Mammoth Cave National Park,7,85,223,1570,1515,1,1,3,6,4,6,2
Mesa Verde National Park,5,58,151,1061,1043,2,1,2,6,5,6,2
Mount Rainier National Park,9,66,156,1121,1079,5,2,4,7,5,4,2
North Cascades National Park,10,133,385,2519,1531,2,1,3,6,5,6,2
Olympic National Park,6,75,204,1251,1218,2,1,3,6,5,5,2
Petrified Forest National Park,5,46,111,688,679,2,1,2,6,5,4,2
Pinnacles National Park,8,74,184,933,865,2,1,3,6,5,5,2
Redwood National Park,6,86,228,1489,1355,2,1,3,6,5,6,2
Rocky Mountain National Park,12,118,287,1782,1452,2,1,3,6,5,5,2
Saguaro National Park,5,60,177,1504,1497,3,2,3,7,5,4,2
Sequoia and Kings Canyon National Parks,6,77,202,1806,1711,1,1,3,6,5,7,2
Shenandoah National Park,10,136,379,2536,1778,2,1,3,6,5,6,2
Theodore Roosevelt National Park,5,56,133,648,625,1,1,3,6,3,3,2
Voyageurs National Park,7,86,198,1149,1145,2,1,2,6,5,6,2
Wind Cave National Park,5,62,154,778,772,2,1,3,6,4,6,2
Wrangell - St Elias National Park and Preserve,8,64,143,1347,1123,1,1,2,6,5,4,2
Yellowstone National Park,9,76,237,2172,1453,2,1,3,6,5,6,2
Yosemite National Park,6,76,203,1883,1731,1,1,3,6,5,6,2
Zion National Park,6,68,186,1293,1279,2,1,3,6,5,6,2

In [ ]:
park_name_list = species_df['Park_name'].unique()
park_name_list

Acadia_df = species_df.copy(deep=True)

# selecting rows based on condition
Acadia_df = Acadia_df.loc[Acadia_df['Park_name'] == 'Acadia National Park']
  
Acadia_df

num_species = Acadia_df['Scientific_name'].nunique()
num_species
print(num_species)

num_species_native = Acadia_df.loc[Acadia_df['Nativeness'] == 'Native', 'Scientific_name'].count()
print(num_species_native)

num_species_not_native = Acadia_df.loc[Acadia_df['Nativeness'] != 'Native', 'Scientific_name'].count()
print(num_species_not_native)

perc_native = (num_species_native/num_species)*100

print(perc_native)

In [ ]:
Acadia_df.head()

### Defining % Species which are Native and adding to the Parks info

In [ ]:
perc_native_dict = {'num_species':[], 'perc_native':[]}


for park in park_name_list:
    native_df = species_df.copy(deep=True)
    native_df = native_df.loc[native_df['Park_name'] == str(park)]
    num_species = native_df['Scientific_name'].nunique()
    num_species_native = native_df.loc[native_df['Nativeness'] == 'Native', 'Scientific_name'].count()
    perc_native = (num_species_native/num_species)*100
    perc_native_dict['num_species'].append(num_species)
    perc_native_dict['perc_native'].append(perc_native)
    
#print(perc_native_dict)
#print(len(perc_native_dict['num_species']))
#print(perc_native_dict['perc_native'])

In [ ]:
parks_df_native = parks_df.copy(deep=True)
perc_native_df =pd.DataFrame(perc_native_dict)
perc_native_df.head()

combo_df = pd.concat([parks_df_native, perc_native_df], axis=1)
combo_df

#parks_df_copy = parks_df_copy.append(perc_native_df, ignore_index=True)
#parks_df_copy.head()

#print(perc_native_dict)

In [ ]:
agg_df2 = parks_df.copy(deep = True)
agg_df2.head()

In [ ]:
aggregate_dict = {'num_species':[], 'perc_native':[],'num_categories_present':[], 'num_orders_present':[], 
                  'num_families_present':[],'num_rare':[], 'num_uncommon':[], 'perc_uncommon_rare':[], 
                  'num_protected':[], 'perc_protected':[],'num_endangered':[], 'perc_endangered':[], 
                  'num_plants':[], 'num_animals':[], 'perc_plants':[], }


for park in park_name_list:
    agg_df = species_df.copy(deep=True)
    agg_df = agg_df.loc[agg_df['Park_name'] == str(park)]
       
    num_species = agg_df['Scientific_name'].nunique()
    num_species_native = agg_df.loc[agg_df['Nativeness'] == 'Native', 'Scientific_name'].count()
    perc_native = (num_species_native/num_species)*100
    aggregate_dict['num_species'].append(num_species)
    aggregate_dict['perc_native'].append(perc_native)
    
  
    num_categories_present = agg_df['Category'].nunique()
    num_orders_present = agg_df['Order'].nunique()
    num_families_present = agg_df['Family'].nunique()
    num_rare = agg_df.loc[agg_df['Abundance'] == 'Rare', 'Scientific_name'].count() 
    num_uncommon = agg_df.loc[agg_df['Abundance'] == 'Uncommon', 'Scientific_name'].count() 
    perc_uncommon_rare = ((num_rare + num_uncommon)/num_species)*100
    num_concern = agg_df.loc[agg_df['Conservation_status'] == 'Species of Concern', 'Scientific_name'].count() 
    num_prop_threatened = agg_df.loc[agg_df['Conservation_status'] == 'Proposed Threatened', 'Scientific_name'].count() 
    num_threatened = agg_df.loc[agg_df['Conservation_status'] == 'Threatened', 'Scientific_name'].count() 
    num_prop_endangered = agg_df.loc[agg_df['Conservation_status'] == 'Proposed Endangered', 'Scientific_name'].count()
    num_endangered = agg_df.loc[agg_df['Conservation_status'] == 'Endangered', 'Scientific_name'].count() 
    num_protected = num_prop_threatened + num_concern + num_threatened + num_prop_endangered + num_endangered
    perc_protected = (num_protected/num_species)*100
    perc_endangered = ((num_prop_endangered + num_endangered)/num_species)*100
    num_plants = agg_df.loc[agg_df['plant_animal_boolean'] == 0, 'Scientific_name'].count() 
    num_animals = num_species - num_plants
    perc_plants = (num_plants/num_species)*100

    aggregate_dict['num_categories_present'].append(num_categories_present)
    aggregate_dict['num_orders_present'].append(num_orders_present)
    aggregate_dict['num_families_present'].append(num_families_present)
    aggregate_dict['num_rare'].append(num_rare)
    aggregate_dict['num_uncommon'].append(num_categories_present)
    aggregate_dict['perc_uncommon_rare'].append(perc_uncommon_rare)

    aggregate_dict['num_protected'].append(num_protected)
    aggregate_dict['perc_protected'].append(perc_protected)
    aggregate_dict['num_endangered'].append(num_endangered)
    aggregate_dict['perc_endangered'].append(perc_endangered)
    aggregate_dict['num_plants'].append(num_plants)
    aggregate_dict['num_animals'].append(num_animals)
    aggregate_dict['perc_plants'].append(perc_plants)

In [ ]:
agg_calcs_df_2 = agg_df2.copy(deep=True)
agg_calcs_df =pd.DataFrame(aggregate_dict)
agg_calcs_df.head()

biodiversity_df = pd.concat([agg_calcs_df_2, agg_calcs_df], axis=1)
biodiversity_df.columns

### Maps

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
biodiversity_df.head()

### Defining a function to make plotting on maps easy and replicable

In [ ]:
def mapping_function(df, desc1, desc2, col1, col2, col3, rgb_line, rgb_land, colorscale, fig_title):
    #df = dataframe, desc1 = text desired to describe info in col2, desc2 = text desired to describe info in col 3,
    #col1 = desired nominal col for labels, col2 = col correlated to size of points in scatterplot,
    #col3 = col correlated to color of points in scatterplot, rgb_line = color of lines around points in scatterplot,
    #rgb_land = color of background map land, colorscale = colorscale to be used for scatterplot points
    
    #defining text labels for scatter plot on map
    df['text'] = df[str(col1)] + '<br>' + \
        (df[str(col2)]).astype(str) + str(desc1) + '<br>' + \
        (df[str(col3)]).astype(str) + 'desc2'
    
    #setting the scale. We will keep this constant at 8000 as it seems to work well.
    scale = 8000
    
    #defining the figure as a geo-objects figure
    fig = go.Figure()
    
    #Adding the code to create a scatterplot. Here we are only interested in US map, so it's hardcoded as such.
    #This could easily be converted as a variable. Lat and Long coordinates are defined and text for markers is called.
    #Everything about markers is set.
    fig.add_trace(go.Scattergeo(
        locationmode = 'USA-states',
        lon = df['Longitude'],
        lat = df['Latitude'],
        text = df['text'],
        marker = dict(
            size = df[str(col2)] / scale,
            color = df[str(col3)],
            line_color = str(rgb_line),
            line_width = 0.75,
            sizemode = 'area',
            colorscale_map = str(colorscale),
            cmax = df[str(col3)].max(),
            cmin = df[str(col3)].min(),
            colorbar = {'title': str(colorbar_title)}
            )))
    
    fig.update_layout(
        title_text = str(fig_title),
        geo = dict(
            scope = 'usa',
            landcolor = str(rgb_land) 
        )
    )

    fig.show()

In [ ]:
biodiversity_df['Park_text'] = biodiversity_df['Park_name'] + '<br>' + \
    (biodiversity_df['Acres']).astype(str) + ' Park size in Acres' + '<br>' + \
    (biodiversity_df['num_species']).astype(str)+' Unique Species'

In [ ]:
scale = 8000

In [ ]:
#Add comments and adjust
fig = go.Figure()

#for index, row in geo_parks.iterrows():
fig.add_trace(go.Scattergeo(
    locationmode = 'USA-states',
    lon = biodiversity_df['Longitude'],
    lat = biodiversity_df['Latitude'],
    text = biodiversity_df['Park_text'],
    marker = dict(
        size = biodiversity_df['Acres']/scale,
        color = biodiversity_df['num_species'],
        line_color='rgb(8, 8, 8)',
        line_width=0.75,
        sizemode = 'area',
        colorscale = 'RdYlBu',
        cmax = biodiversity_df['num_species'].max(),
        cmin = biodiversity_df['num_species'].min(),
        colorbar = {'title': 'Number of Species'}
        )))


fig.update_layout(
        title_text = 'Total Biodiversity and Size (in Acres) of US National Parks',
        geo = dict(
            scope = 'usa',
            landcolor = rgb(180, 180, 180)
        )
    )

fig.show()

### Considering Unique Species

In [29]:
species_df.columns

Index(['Park_name', 'Category', 'Order', 'Family', 'Scientific_name',
       'Common_name', 'Record_status', 'Occurrence', 'Nativeness', 'Abundance',
       'Seasonality', 'Conservation_status', 'plant_animal_boolean'],
      dtype='object')

In [30]:
def drop_dup(df, col):
    new_df = df.copy(deep=True)
    new_df.drop_duplicates(subset=str(col))
    
unique_species = drop_dup(species_df, 'Scientific_name')
print(unique_species)

None

In [31]:
unique_species_df = species_df.copy(deep=True)
unique_species_df = unique_species_df.drop_duplicates(subset = 'Scientific_name', keep = False)
unique_species_df

print(unique_species_df.shape)

unique_species_df.groupby('Park_name').count()['Order'].sum()

(13367, 13)

13175

### Encoding

Almost all of our data (especially for the species_df) is categorical. Therefore, we need to do some label encoding before we can appropriately create and train our models. We handle abundance and conservation status separately from the rest of the column encoding-details and motivation are shared below.

#### Abundance and Conservation_status:

These categories are ordinal, meaning that there IS a value associated with the category labels. Here, we encode those data such that: for Abundance, the most rare organisms are assigned a score of 1 and the most abundant are assigned the highest score. Organisms with no abundance data have not been included (have been removed from the dataframe). For conservation_status, if no information is given, the assigned value with be 0 and the most endangered animals will be assigned the highest values.

#### Encoding Abundance

In [32]:
species_df['Abundance'].unique()

array(['Rare', 'Common', 'Occasional', 'Abundant', 'Uncommon', 'Unknown',
       'Entry_error'], dtype=object)

In [33]:
Abundance_dict = {'Unknown' : 0, 'Rare' : 1, 'Uncommon' : 2, 'Occasional' : 3, 'Common' : 4, 'Abundant' : 5}

species_df_encoded = species_df.copy(deep=True)

In [34]:
species_df_encoded ['Abundance'] = species_df_encoded.Abundance.map(Abundance_dict)
species_df_encoded.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,1.0,Resident,None_given,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,4.0,Breeder,None_given,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,4.0,Breeder,None_given,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,3.0,Migratory,None_given,1
28,Acadia National Park,Mammal,Lagomorpha,Leporidae,Lepus americanus,"Snowshoe Hare, Varying Hare",Approved,Present,Native,4.0,Breeder,None_given,1

In [35]:
species_df_encoded['Abundance'].unique()

array([ 1.,  4.,  3.,  5.,  2.,  0., nan])

In [36]:
species_df_encoded.dropna(subset = ['Abundance'], inplace=True)
species_df_encoded

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,1.0,Resident,None_given,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,4.0,Breeder,None_given,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,4.0,Breeder,None_given,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,3.0,Migratory,None_given,1
28,Acadia National Park,Mammal,Lagomorpha,Leporidae,Lepus americanus,"Snowshoe Hare, Varying Hare",Approved,Present,Native,4.0,Breeder,None_given,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,2.0,Plant,None_given,0
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,2.0,Plant,None_given,0
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,2.0,Plant,None_given,0
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,1.0,Plant,None_given,0
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,2.0,Plant,None_given,0

In [37]:
#check to make sure NaNs are really gone
species_df_encoded['Abundance'].unique()

array([1., 4., 3., 5., 2., 0.])

In [38]:
species_df_encoded ['Abundance'] = species_df_encoded ['Abundance'].astype(int)
species_df_encoded

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,1,Resident,None_given,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,4,Breeder,None_given,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,4,Breeder,None_given,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,3,Migratory,None_given,1
28,Acadia National Park,Mammal,Lagomorpha,Leporidae,Lepus americanus,"Snowshoe Hare, Varying Hare",Approved,Present,Native,4,Breeder,None_given,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Approved,Present,Native,2,Plant,None_given,0
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Approved,Present,Native,2,Plant,None_given,0
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Approved,Present,Not Native,2,Plant,None_given,0
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Approved,Present,Native,1,Plant,None_given,0
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Approved,Present,Not Native,2,Plant,None_given,0

#### Encoding Conservation_Status

In [39]:
species_df['Conservation_status'].unique()

array(['None_given', 'Species of Concern', 'In Recovery', 'Under Review',
       'Endangered', 'Threatened', 'Proposed Threatened',
       'Proposed Endangered'], dtype=object)

In [40]:
species_df['Conservation_status'].value_counts()

None_given             66415
Species of Concern      2709
Endangered               152
Under Review             106
Threatened               104
In Recovery               60
Proposed Endangered       15
Proposed Threatened        2
Name: Conservation_status, dtype: int64

In [41]:
Conservation_dict = {'None_given' : 0, 'Under Review' : 1, 'In Recovery' : 2, 'Species of Concern' : 3, 'Proposed Threatened' : 4, 'Threatened' : 5, 'Proposed Endangered' : 6, 'Endangered' : 7}

species_df_encoded_cons = species_df_encoded.copy(deep=True)

In [42]:
species_df_encoded_cons ['Conservation_status'] = species_df_encoded_cons.Conservation_status.map(Conservation_dict)
species_df_encoded_cons.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,1,Resident,0,1
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,4,Breeder,0,1
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Approved,Present,Native,4,Breeder,0,1
22,Acadia National Park,Mammal,Chiroptera,Vespertilionidae,Lasiurus borealis,"Eastern Red Bat, New York Bat, Northern Red Ba...",Approved,Present,Native,3,Migratory,0,1
28,Acadia National Park,Mammal,Lagomorpha,Leporidae,Lepus americanus,"Snowshoe Hare, Varying Hare",Approved,Present,Native,4,Breeder,0,1

#### Encoding other data

In [43]:
#this data is primarily text
#so we will need to do some label encoding before we can create and train data models

#label encode Park Name
from sklearn.preprocessing import LabelEncoder
class_labels = LabelEncoder()

def LabelEncode (df, col_list):
    for col in df[col_list]:
        df[col] = class_labels.fit_transform(df[col].values)

In [44]:
#label encode species dataframe
col_list = ['Park_name', 'Category', 'Order', 'Family', 'Scientific_name', 'Nativeness', 'Seasonality', 'Record_status', 'Occurrence']

species_final_enc = species_df_encoded_cons.copy(deep = True)
LabelEncode(species_final_enc, col_list)
species_final_enc.head()

,Park_name,Category,Order,Family,Scientific_name,Common_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,0,8,29,260,585,Moose,0,0,0,1,3,0,1
4,0,8,61,220,24293,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",0,0,2,4,0,0,1
8,0,8,61,831,13730,"Otter, River Otter",0,0,0,4,0,0,1
22,0,8,72,1366,12526,"Eastern Red Bat, New York Bat, Northern Red Ba...",0,0,0,3,1,0,1
28,0,8,178,708,12908,"Snowshoe Hare, Varying Hare",0,0,0,4,0,0,1

### Filtering the data: Removing Common Names column

Scientific names should be unique and may be useful later on. Common names on the other hand are useful for human understanding but a) there are many names for some organisms so there is a question of which is the most common common name and b) encoding the scientific names are likely more useful for machine learning/modeling

In [47]:
species_final = species_final_enc.copy(deep=True)

species_final = species_final_enc.drop(labels = ["Common_name"], axis = 1)

species_final.head()

,Park_name,Category,Order,Family,Scientific_name,Record_status,Occurrence,Nativeness,Abundance,Seasonality,Conservation_status,plant_animal_boolean
0,0,8,29,260,585,0,0,0,1,3,0,1
4,0,8,61,220,24293,0,0,2,4,0,0,1
8,0,8,61,831,13730,0,0,0,4,0,0,1
22,0,8,72,1366,12526,0,0,0,3,1,0,1
28,0,8,178,708,12908,0,0,0,4,0,0,1

### Modeling to Predict "Conservation Status"

In [50]:
#how many labels are in the Nativeness column?
species_final["Conservation_status"].value_counts()

0    66379
3     2709
7      152
1      106
5      104
2       60
6       15
4        2
Name: Conservation_status, dtype: int64

In [63]:
#that is an awful lot of 0 ("Not_given") values
#create alternate version of dataset without Not_given values,
#run models on both to compare

species_final_no0 = species_final[species_final['Conservation_status'].isin(
    [3, 7, 1, 5, 2, 6, 4])]
species_final_no0['Conservation_status'].value_counts()

3    2709
7     152
1     106
5     104
2      60
6      15
4       2
Name: Conservation_status, dtype: int64

In [51]:
#check data types - see if our label encoding behaved
species_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69527 entries, 0 to 119247
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Park_name             69527 non-null  int64
 1   Category              69527 non-null  int64
 2   Order                 69527 non-null  int64
 3   Family                69527 non-null  int64
 4   Scientific_name       69527 non-null  int64
 5   Record_status         69527 non-null  int64
 6   Occurrence            69527 non-null  int64
 7   Nativeness            69527 non-null  int64
 8   Abundance             69527 non-null  int64
 9   Seasonality           69527 non-null  int64
 10  Conservation_status   69527 non-null  int64
 11  plant_animal_boolean  69527 non-null  int64
dtypes: int64(12)
memory usage: 6.9 MB

In [64]:
species_final_no0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3148 entries, 57 to 118992
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Park_name             3148 non-null   int64
 1   Category              3148 non-null   int64
 2   Order                 3148 non-null   int64
 3   Family                3148 non-null   int64
 4   Scientific_name       3148 non-null   int64
 5   Record_status         3148 non-null   int64
 6   Occurrence            3148 non-null   int64
 7   Nativeness            3148 non-null   int64
 8   Abundance             3148 non-null   int64
 9   Seasonality           3148 non-null   int64
 10  Conservation_status   3148 non-null   int64
 11  plant_animal_boolean  3148 non-null   int64
dtypes: int64(12)
memory usage: 319.7 KB

In [65]:
#Logistic Regression - set A
#import train_test_split
from sklearn.model_selection import train_test_split

X = species_final.drop('Conservation_status', axis=1)
y = species_final['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [66]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [67]:
#set up Logistic Regression model
from sklearn.linear_model import LogisticRegression

regression_cs = LogisticRegression()
regression_cs.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [68]:
#check performance of regression model
regression_cs.fit(X_train, y_train)
y_pred = regression_cs.predict(X_test)
regression_cs.score(X_test, y_test)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9546958147562203

In [70]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_rev = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_rev)

0.7144921729114554

In [71]:
#Logistic Regression - set B
#import train_test_split

X = species_final_no0.drop('Conservation_status', axis=1)
y = species_final_no0['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [72]:
#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [73]:
regression_cs = LogisticRegression()
regression_cs.fit(X_train, y_train)

LogisticRegression()

In [74]:
#check performance of regression model
regression_cs.fit(X_train, y_train)
y_pred = regression_cs.predict(X_test)
regression_cs.score(X_test, y_test)

0.8603174603174604

In [75]:
#import MSE - check RMSE
from sklearn.metrics import mean_squared_error as MSE

rmse_log_rev = MSE(y_test, y_pred) ** (1/2)
print(rmse_log_rev)

1.0563489082083704

### Decision Trees

In [84]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [85]:
#dataset a

X = species_final.drop('Conservation_status', axis=1)
y = species_final['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [86]:
dt_cs = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_cs.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [87]:
y_pred = dt_cs.predict(X_test)

dt_cs_score = accuracy_score(y_test, y_pred)
print(dt_cs_score)

0.9589385876600028

In [90]:
#check rmse
rmse_dt_cs = MSE(y_test, y_pred) ** (1/2)
print(rmse_dt_cs)

0.6827896012535907

In [91]:
#dataset b

X = species_final_no0.drop('Conservation_status', axis=1)
y = species_final_no0['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [92]:
dt_cs = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_cs.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [94]:
y_pred = dt_cs.predict(X_test)

dt_cs_score = accuracy_score(y_test, y_pred)
print(dt_cs_score)

0.8761904761904762

In [95]:
#check rmse
rmse_dt_cs = MSE(y_test, y_pred) ** (1/2)
print(rmse_dt_cs)

1.025082265378565

### Random Forest

In [101]:
#Random Forest - dataset a
from sklearn.ensemble import RandomForestRegressor

#set seed
SEED = 42

X = species_final.drop('Conservation_status', axis=1)
y = species_final['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = SEED)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [97]:
rf_cs = RandomForestRegressor(n_estimators = 400, min_samples_leaf = 0.1, random_state = SEED)
rf_cs.fit(X_train, y_train)

RandomForestRegressor(min_samples_leaf=0.1, n_estimators=400, random_state=42)

In [99]:
y_pred = rf_cs.predict(X_test)

rmse_rf_cs = MSE(y_test, y_pred) ** (1/2)
print(rmse_rf_cs)

0.6690182731766449

In [102]:
#Random Forest - dataset b
#set seed
SEED = 42

X = species_final_no0.drop('Conservation_status', axis=1)
y = species_final_no0['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = SEED)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [103]:
rf_cs = RandomForestRegressor(n_estimators = 400, min_samples_leaf = 0.1, random_state = SEED)
rf_cs.fit(X_train, y_train)

RandomForestRegressor(min_samples_leaf=0.1, n_estimators=400, random_state=42)

In [104]:
y_pred = rf_cs.predict(X_test)

rmse_rf_cs = MSE(y_test, y_pred) ** (1/2)
print(rmse_rf_cs)

1.130288894615673

### Neural Network

In [105]:
#neural network imports
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [106]:
#dataset a

X = species_final.drop('Conservation_status', axis=1)
y = species_final['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

number_features = X_train.shape[1]

In [111]:
#defining the model
model_cs = Sequential()
model_cs.add(Dense(100, activation='relu', kernel_initializer='he_normal', input_shape=(number_features,)))
model_cs.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model_cs.add(Dense(8, activation='softmax'))

In [112]:
model_cs.compile(optimizer='adam', loss='sparse_categorical_crossentropy', 
                  metrics=['accuracy'])

In [113]:
model_cs.fit(X_train, y_train, epochs=100, batch_size=100, verbose=2)

Epoch 1/100
557/557 - 1s - loss: 0.2164 - accuracy: 0.9442
Epoch 2/100
557/557 - 1s - loss: 0.1618 - accuracy: 0.9553
Epoch 3/100
557/557 - 1s - loss: 0.1581 - accuracy: 0.9558
Epoch 4/100
557/557 - 1s - loss: 0.1548 - accuracy: 0.9563
Epoch 5/100
557/557 - 1s - loss: 0.1528 - accuracy: 0.9565
Epoch 6/100
557/557 - 1s - loss: 0.1508 - accuracy: 0.9565
Epoch 7/100
557/557 - 1s - loss: 0.1492 - accuracy: 0.9568
Epoch 8/100
557/557 - 1s - loss: 0.1481 - accuracy: 0.9567
Epoch 9/100
557/557 - 1s - loss: 0.1466 - accuracy: 0.9569
Epoch 10/100
557/557 - 1s - loss: 0.1450 - accuracy: 0.9567
Epoch 11/100
557/557 - 1s - loss: 0.1438 - accuracy: 0.9571
Epoch 12/100
557/557 - 1s - loss: 0.1428 - accuracy: 0.9571
Epoch 13/100
557/557 - 1s - loss: 0.1415 - accuracy: 0.9576
Epoch 14/100
557/557 - 1s - loss: 0.1406 - accuracy: 0.9576
Epoch 15/100
557/557 - 1s - loss: 0.1393 - accuracy: 0.9575
Epoch 16/100
557/557 - 1s - loss: 0.1386 - accuracy: 0.9580
Epoch 17/100
557/557 - 1s - loss: 0.1372 - accuracy: 0.9581
Epoch 18/100
557/557 - 1s - loss: 0.1366 - accuracy: 0.9586
Epoch 19/100
557/557 - 1s - loss: 0.1358 - accuracy: 0.9581
Epoch 20/100
557/557 - 1s - loss: 0.1342 - accuracy: 0.9587
Epoch 21/100
557/557 - 1s - loss: 0.1342 - accuracy: 0.9582
Epoch 22/100
557/557 - 1s - loss: 0.1332 - accuracy: 0.9588
Epoch 23/100
557/557 - 1s - loss: 0.1325 - accuracy: 0.9591
Epoch 24/100
557/557 - 1s - loss: 0.1319 - accuracy: 0.9589
Epoch 25/100
557/557 - 1s - loss: 0.1310 - accuracy: 0.9587
Epoch 26/100
557/557 - 1s - loss: 0.1302 - accuracy: 0.9592
Epoch 27/100
557/557 - 1s - loss: 0.1300 - accuracy: 0.9591
Epoch 28/100
557/557 - 1s - loss: 0.1287 - accuracy: 0.9600
Epoch 29/100
557/557 - 1s - loss: 0.1278 - accuracy: 0.9597
Epoch 30/100
557/557 - 1s - loss: 0.1275 - accuracy: 0.9599
Epoch 31/100
557/557 - 1s - loss: 0.1270 - accuracy: 0.9597
Epoch 32/100
557/557 - 1s - loss: 0.1267 - accuracy: 0.9601
Epoch 33/100
557/557 - 1s - loss: 0.1266 - accuracy: 0.9598
Epoch 34/100
557/557 - 1s - loss: 0.1247 - accuracy: 0.9601
Epoch 35/100
557/557 - 1s - loss: 0.1248 - accuracy: 0.9598
Epoch 36/100
557/557 - 1s - loss: 0.1242 - accuracy: 0.9606
Epoch 37/100
557/557 - 1s - loss: 0.1240 - accuracy: 0.9602
Epoch 38/100
557/557 - 1s - loss: 0.1235 - accuracy: 0.9603
Epoch 39/100
557/557 - 1s - loss: 0.1234 - accuracy: 0.9606
Epoch 40/100
557/557 - 1s - loss: 0.1221 - accuracy: 0.9604
Epoch 41/100
557/557 - 1s - loss: 0.1222 - accuracy: 0.9602
Epoch 42/100
557/557 - 1s - loss: 0.1214 - accuracy: 0.9606
Epoch 43/100
557/557 - 1s - loss: 0.1212 - accuracy: 0.9604
Epoch 44/100
557/557 - 1s - loss: 0.1205 - accuracy: 0.9607
Epoch 45/100
557/557 - 1s - loss: 0.1202 - accuracy: 0.9611
Epoch 46/100
557/557 - 1s - loss: 0.1200 - accuracy: 0.9606
Epoch 47/100
557/557 - 1s - loss: 0.1199 - accuracy: 0.9609
Epoch 48/100
557/557 - 1s - loss: 0.1196 - accuracy: 0.9610
Epoch 49/100
557/557 - 1s - loss: 0.1188 - accuracy: 0.9609
Epoch 50/100
557/557 - 1s - loss: 0.1186 - accuracy: 0.9610
Epoch 51/100
557/557 - 2s - loss: 0.1179 - accuracy: 0.9613
Epoch 52/100
557/557 - 1s - loss: 0.1176 - accuracy: 0.9615
Epoch 53/100
557/557 - 1s - loss: 0.1171 - accuracy: 0.9616
Epoch 54/100
557/557 - 1s - loss: 0.1172 - accuracy: 0.9611
Epoch 55/100
557/557 - 1s - loss: 0.1163 - accuracy: 0.9617
Epoch 56/100
557/557 - 1s - loss: 0.1165 - accuracy: 0.9611
Epoch 57/100
557/557 - 1s - loss: 0.1150 - accuracy: 0.9619
Epoch 58/100
557/557 - 1s - loss: 0.1156 - accuracy: 0.9608
Epoch 59/100
557/557 - 1s - loss: 0.1153 - accuracy: 0.9616
Epoch 60/100
557/557 - 1s - loss: 0.1146 - accuracy: 0.9615
Epoch 61/100
557/557 - 1s - loss: 0.1157 - accuracy: 0.9615
Epoch 62/100
557/557 - 1s - loss: 0.1144 - accuracy: 0.9614
Epoch 63/100
557/557 - 1s - loss: 0.1144 - accuracy: 0.9620
Epoch 64/100
557/557 - 1s - loss: 0.1138 - accuracy: 0.9614
Epoch 65/100
557/557 - 1s - loss: 0.1135 - accuracy: 0.9624
Epoch 66/100
557/557 - 1s - loss: 0.1131 - accuracy: 0.9618
Epoch 67/100
557/557 - 1s - loss: 0.1129 - accuracy: 0.9618
Epoch 68/100
557/557 - 1s - loss: 0.1122 - accuracy: 0.9624
Epoch 69/100
557/557 - 1s - loss: 0.1129 - accuracy: 0.9620
Epoch 70/100
557/557 - 1s - loss: 0.1124 - accuracy: 0.9619
Epoch 71/100
557/557 - 1s - loss: 0.1123 - accuracy: 0.9621
Epoch 72/100
557/557 - 1s - loss: 0.1115 - accuracy: 0.9620
Epoch 73/100
557/557 - 1s - loss: 0.1111 - accuracy: 0.9625
Epoch 74/100
557/557 - 1s - loss: 0.1110 - accuracy: 0.9623
Epoch 75/100
557/557 - 2s - loss: 0.1108 - accuracy: 0.9617
Epoch 76/100
557/557 - 2s - loss: 0.1111 - accuracy: 0.9620
Epoch 77/100
557/557 - 2s - loss: 0.1100 - accuracy: 0.9628
Epoch 78/100
557/557 - 1s - loss: 0.1109 - accuracy: 0.9624
Epoch 79/100
557/557 - 1s - loss: 0.1103 - accuracy: 0.9625
Epoch 80/100
557/557 - 1s - loss: 0.1098 - accuracy: 0.9625
Epoch 81/100
557/557 - 1s - loss: 0.1090 - accuracy: 0.9628
Epoch 82/100
557/557 - 1s - loss: 0.1088 - accuracy: 0.9632
Epoch 83/100
557/557 - 1s - loss: 0.1087 - accuracy: 0.9627
Epoch 84/100
557/557 - 2s - loss: 0.1086 - accuracy: 0.9632
Epoch 85/100
557/557 - 1s - loss: 0.1080 - accuracy: 0.9627
Epoch 86/100
557/557 - 1s - loss: 0.1086 - accuracy: 0.9626
Epoch 87/100
557/557 - 1s - loss: 0.1082 - accuracy: 0.9634
Epoch 88/100
557/557 - 1s - loss: 0.1075 - accuracy: 0.9633
Epoch 89/100
557/557 - 1s - loss: 0.1074 - accuracy: 0.9627
Epoch 90/100
557/557 - 1s - loss: 0.1075 - accuracy: 0.9632
Epoch 91/100
557/557 - 1s - loss: 0.1071 - accuracy: 0.9632
Epoch 92/100
557/557 - 1s - loss: 0.1071 - accuracy: 0.9629
Epoch 93/100
557/557 - 1s - loss: 0.1071 - accuracy: 0.9633
Epoch 94/100
557/557 - 1s - loss: 0.1063 - accuracy: 0.9634
Epoch 95/100
557/557 - 1s - loss: 0.1064 - accuracy: 0.9636
Epoch 96/100
557/557 - 1s - loss: 0.1053 - accuracy: 0.9634
Epoch 97/100
557/557 - 1s - loss: 0.1055 - accuracy: 0.9630
Epoch 98/100
557/557 - 1s - loss: 0.1056 - accuracy: 0.9640
Epoch 99/100
557/557 - 1s - loss: 0.1054 - accuracy: 0.9633
Epoch 100/100
557/557 - 1s - loss: 0.1051 - accuracy: 0.9642

In [114]:
#dataset b

X = species_final_no0.drop('Conservation_status', axis=1)
y = species_final_no0['Conservation_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#scale dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

number_features = X_train.shape[1]

In [115]:
#defining the model
model_cs = Sequential()
model_cs.add(Dense(100, activation='relu', kernel_initializer='he_normal', input_shape=(number_features,)))
model_cs.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model_cs.add(Dense(8, activation='softmax'))

In [116]:
model_cs.compile(optimizer='adam', loss='sparse_categorical_crossentropy', 
                  metrics=['accuracy'])

In [117]:
model_cs.fit(X_train, y_train, epochs=100, batch_size=100, verbose=2)

Epoch 1/100
26/26 - 1s - loss: 1.2011 - accuracy: 0.7081
Epoch 2/100
26/26 - 0s - loss: 0.6314 - accuracy: 0.8646
Epoch 3/100
26/26 - 0s - loss: 0.5587 - accuracy: 0.8634
Epoch 4/100
26/26 - 0s - loss: 0.5247 - accuracy: 0.8650
Epoch 5/100
26/26 - 0s - loss: 0.5003 - accuracy: 0.8670
Epoch 6/100
26/26 - 0s - loss: 0.4810 - accuracy: 0.8678
Epoch 7/100
26/26 - 0s - loss: 0.4667 - accuracy: 0.8674
Epoch 8/100
26/26 - 0s - loss: 0.4556 - accuracy: 0.8705
Epoch 9/100
26/26 - 0s - loss: 0.4468 - accuracy: 0.8725
Epoch 10/100
26/26 - 0s - loss: 0.4392 - accuracy: 0.8749
Epoch 11/100
26/26 - 0s - loss: 0.4285 - accuracy: 0.8769
Epoch 12/100
26/26 - 0s - loss: 0.4190 - accuracy: 0.8761
Epoch 13/100
26/26 - 0s - loss: 0.4106 - accuracy: 0.8801
Epoch 14/100
26/26 - 0s - loss: 0.4033 - accuracy: 0.8852
Epoch 15/100
26/26 - 0s - loss: 0.3978 - accuracy: 0.8828
Epoch 16/100
26/26 - 0s - loss: 0.3914 - accuracy: 0.8888
Epoch 17/100
26/26 - 0s - loss: 0.3891 - accuracy: 0.8852
Epoch 18/100
26/26 - 0s - loss: 0.3818 - accuracy: 0.8888
Epoch 19/100
26/26 - 0s - loss: 0.3775 - accuracy: 0.8884
Epoch 20/100
26/26 - 0s - loss: 0.3689 - accuracy: 0.8916
Epoch 21/100
26/26 - 0s - loss: 0.3668 - accuracy: 0.8912
Epoch 22/100
26/26 - 0s - loss: 0.3636 - accuracy: 0.8940
Epoch 23/100
26/26 - 0s - loss: 0.3567 - accuracy: 0.8963
Epoch 24/100
26/26 - 0s - loss: 0.3514 - accuracy: 0.8944
Epoch 25/100
26/26 - 0s - loss: 0.3450 - accuracy: 0.8983
Epoch 26/100
26/26 - 0s - loss: 0.3453 - accuracy: 0.8983
Epoch 27/100
26/26 - 0s - loss: 0.3410 - accuracy: 0.8963
Epoch 28/100
26/26 - 0s - loss: 0.3315 - accuracy: 0.8991
Epoch 29/100
26/26 - 0s - loss: 0.3327 - accuracy: 0.8979
Epoch 30/100
26/26 - 0s - loss: 0.3315 - accuracy: 0.8987
Epoch 31/100
26/26 - 0s - loss: 0.3258 - accuracy: 0.8999
Epoch 32/100
26/26 - 0s - loss: 0.3217 - accuracy: 0.8987
Epoch 33/100
26/26 - 0s - loss: 0.3203 - accuracy: 0.8987
Epoch 34/100
26/26 - 0s - loss: 0.3140 - accuracy: 0.9015
Epoch 35/100
26/26 - 0s - loss: 0.3098 - accuracy: 0.9031
Epoch 36/100
26/26 - 0s - loss: 0.3039 - accuracy: 0.9035
Epoch 37/100
26/26 - 0s - loss: 0.3088 - accuracy: 0.9011
Epoch 38/100
26/26 - 0s - loss: 0.2975 - accuracy: 0.9055
Epoch 39/100
26/26 - 0s - loss: 0.2939 - accuracy: 0.9063
Epoch 40/100
26/26 - 0s - loss: 0.2945 - accuracy: 0.9039
Epoch 41/100
26/26 - 0s - loss: 0.2915 - accuracy: 0.9031
Epoch 42/100
26/26 - 0s - loss: 0.2882 - accuracy: 0.9095
Epoch 43/100
26/26 - 0s - loss: 0.2805 - accuracy: 0.9047
Epoch 44/100
26/26 - 0s - loss: 0.2795 - accuracy: 0.9067
Epoch 45/100
26/26 - 0s - loss: 0.2740 - accuracy: 0.9087
Epoch 46/100
26/26 - 0s - loss: 0.2726 - accuracy: 0.9087
Epoch 47/100
26/26 - 0s - loss: 0.2754 - accuracy: 0.9071
Epoch 48/100
26/26 - 0s - loss: 0.2696 - accuracy: 0.9075
Epoch 49/100
26/26 - 0s - loss: 0.2700 - accuracy: 0.9098
Epoch 50/100
26/26 - 0s - loss: 0.2620 - accuracy: 0.9106
Epoch 51/100
26/26 - 0s - loss: 0.2583 - accuracy: 0.9098
Epoch 52/100
26/26 - 0s - loss: 0.2581 - accuracy: 0.9130
Epoch 53/100
26/26 - 0s - loss: 0.2553 - accuracy: 0.9138
Epoch 54/100
26/26 - 0s - loss: 0.2527 - accuracy: 0.9142
Epoch 55/100
26/26 - 0s - loss: 0.2511 - accuracy: 0.9154
Epoch 56/100
26/26 - 0s - loss: 0.2470 - accuracy: 0.9150
Epoch 57/100
26/26 - 0s - loss: 0.2468 - accuracy: 0.9150
Epoch 58/100
26/26 - 0s - loss: 0.2370 - accuracy: 0.9190
Epoch 59/100
26/26 - 0s - loss: 0.2477 - accuracy: 0.9138
Epoch 60/100
26/26 - 0s - loss: 0.2377 - accuracy: 0.9186
Epoch 61/100
26/26 - 0s - loss: 0.2340 - accuracy: 0.9218
Epoch 62/100
26/26 - 0s - loss: 0.2314 - accuracy: 0.9202
Epoch 63/100
26/26 - 0s - loss: 0.2314 - accuracy: 0.9202
Epoch 64/100
26/26 - 0s - loss: 0.2333 - accuracy: 0.9253
Epoch 65/100
26/26 - 0s - loss: 0.2300 - accuracy: 0.9237
Epoch 66/100
26/26 - 0s - loss: 0.2303 - accuracy: 0.9174
Epoch 67/100
26/26 - 0s - loss: 0.2255 - accuracy: 0.9226
Epoch 68/100
26/26 - 0s - loss: 0.2279 - accuracy: 0.9234
Epoch 69/100
26/26 - 0s - loss: 0.2200 - accuracy: 0.9234
Epoch 70/100
26/26 - 0s - loss: 0.2143 - accuracy: 0.9265
Epoch 71/100
26/26 - 0s - loss: 0.2216 - accuracy: 0.9190
Epoch 72/100
26/26 - 0s - loss: 0.2165 - accuracy: 0.9190
Epoch 73/100
26/26 - 0s - loss: 0.2084 - accuracy: 0.9293
Epoch 74/100
26/26 - 0s - loss: 0.2072 - accuracy: 0.9273
Epoch 75/100
26/26 - 0s - loss: 0.2101 - accuracy: 0.9269
Epoch 76/100
26/26 - 0s - loss: 0.2080 - accuracy: 0.9265
Epoch 77/100
26/26 - 0s - loss: 0.2059 - accuracy: 0.9257
Epoch 78/100
26/26 - 0s - loss: 0.2029 - accuracy: 0.9281
Epoch 79/100
26/26 - 0s - loss: 0.2021 - accuracy: 0.9285
Epoch 80/100
26/26 - 0s - loss: 0.2019 - accuracy: 0.9277
Epoch 81/100
26/26 - 0s - loss: 0.1969 - accuracy: 0.9321
Epoch 82/100
26/26 - 0s - loss: 0.1976 - accuracy: 0.9325
Epoch 83/100
26/26 - 0s - loss: 0.1910 - accuracy: 0.9297
Epoch 84/100
26/26 - 0s - loss: 0.1920 - accuracy: 0.9313
Epoch 85/100
26/26 - 0s - loss: 0.1950 - accuracy: 0.9273
Epoch 86/100
26/26 - 0s - loss: 0.1905 - accuracy: 0.9345
Epoch 87/100
26/26 - 0s - loss: 0.1891 - accuracy: 0.9321
Epoch 88/100
26/26 - 0s - loss: 0.1848 - accuracy: 0.9353
Epoch 89/100
26/26 - 0s - loss: 0.1857 - accuracy: 0.9341
Epoch 90/100
26/26 - 0s - loss: 0.1847 - accuracy: 0.9349
Epoch 91/100
26/26 - 0s - loss: 0.1885 - accuracy: 0.9317
Epoch 92/100
26/26 - 0s - loss: 0.1885 - accuracy: 0.9289
Epoch 93/100
26/26 - 0s - loss: 0.1837 - accuracy: 0.9321
Epoch 94/100
26/26 - 0s - loss: 0.1744 - accuracy: 0.9361
Epoch 95/100
26/26 - 0s - loss: 0.1880 - accuracy: 0.9357
Epoch 96/100
26/26 - 0s - loss: 0.1826 - accuracy: 0.9353
Epoch 97/100
26/26 - 0s - loss: 0.1748 - accuracy: 0.9392
Epoch 98/100
26/26 - 0s - loss: 0.1764 - accuracy: 0.9357
Epoch 99/100
26/26 - 0s - loss: 0.1719 - accuracy: 0.9392
Epoch 100/100
26/26 - 0s - loss: 0.1721 - accuracy: 0.9380